**Problem:**

You are given the following dataset:
1. **Audible Data** : https://1drv.ms/u/s!AiqdXCxPTydhoog8ckLN-6Cw55fzIg?e=EWgZ5d


The link not working right now. Data can be found here: https://www.kaggle.com/datasets/snehangsude/audible-dataset/data

Your task is to:
- Find the problems with the datasets.
- Define the Data Quality Dimensions.
- Try to clean the datasets.

In [2]:
!pip install kagglehub

Collecting kagglehub
  Downloading kagglehub-1.0.0-py3-none-any.whl.metadata (40 kB)
     ---------------------------------------- 0.0/40.1 kB ? eta -:--:--
     ---------- ----------------------------- 10.2/40.1 kB ? eta -:--:--
     ---------- ----------------------------- 10.2/40.1 kB ? eta -:--:--
     ------------------- ------------------ 20.5/40.1 kB 131.3 kB/s eta 0:00:01
     ----------------------------- -------- 30.7/40.1 kB 186.2 kB/s eta 0:00:01
     -------------------------------------- 40.1/40.1 kB 191.2 kB/s eta 0:00:00
Collecting kagglesdk<1.0,>=0.1.14 (from kagglehub)
  Downloading kagglesdk-0.1.16-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: packaging in d:\software\anaconda\lib\site-packages (from kagglehub) (23.2)
Requirement already satisfied: pyyaml in d:\software\anaconda\lib\site-packages (from kagglehub) (6.0.1)
Requirement already satisfied: requests in d:\software\anaconda\lib\site-packages (from kagglehub) (2.32.5)
Requirement already satisfied: tqdm in d:\software\anaconda\lib\site-packages (from kagglehub) (4.66.4)
Requirement already satisfied: protobuf in d:\software\anaconda\lib\site-packages (from kagglesdk<1.0,>=0.1.14->kagglehub) (3.20.3)
Requirement already satisfied: charset_normalizer<4,>=2 in d:\software\anaconda\lib\site-packages (from requests->kagglehub) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in d:\software\anaconda\lib\site-packages (from requests->kagglehub) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in d:\software\anaconda\lib\site-packages (from requests->kagglehub) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in d:\software\anaconda\lib\site-packages (from requests->kagglehub) (2025.8.3)
Requirement already satisfied: colorama in d:\software\anaconda\lib\site-packages (from tqdm->kagglehub) (0.4.6)
Downloading kagglehub-1.0.0-py3-none-any.whl (70 kB)
   ---------------------------------------- 0.0/70.6 kB ? eta -:--:--
   ----------------- ---------------------- 30.7/70.6 kB 1.3 MB/s eta 0:00:01
   ---------------------------------- ----- 61.4/70.6 kB 1.1 MB/s eta 0:00:01
   ---------------------------------------- 70.6/70.6 kB 958.6 kB/s eta 0:00:00
Downloading kagglesdk-0.1.16-py3-none-any.whl (160 kB)
   ---------------------------------------- 0.0/160.5 kB ? eta -:--:--
   ---------------------------- ----------- 112.6/160.5 kB 6.8 MB/s eta 0:00:01
   ---------------------------------------- 160.5/160.5 kB 2.4 MB/s eta 0:00:00
Installing collected packages: kagglesdk, kagglehub
Successfully installed kagglehub-1.0.0 kagglesdk-0.1.16

In [3]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("snehangsude/audible-dataset")

print("Path to dataset files:", path)

Downloading to C:\Users\Tanvir Ahmed\.cache\kagglehub\datasets\snehangsude\audible-dataset\1.archive...

100%|██████████| 6.24M/6.24M [00:06<00:00, 1.05MB/s]

Extracting files...

Path to dataset files: C:\Users\Tanvir Ahmed\.cache\kagglehub\datasets\snehangsude\audible-dataset\versions\1

In [4]:
import pandas as pd
import numpy as np

In [5]:
#getting the main file using readcsv method
main_copy = pd.read_csv("audible_uncleaned.csv")
main_copy.head()

,name,author,narrator,time,releasedate,language,stars,price
0,Geronimo Stilton #11 & #12,Writtenby:GeronimoStilton,Narratedby:BillLobely,2 hrs and 20 mins,04-08-08,English,5 out of 5 stars34 ratings,468.00
1,The Burning Maze,Writtenby:RickRiordan,Narratedby:RobbieDaymond,13 hrs and 8 mins,01-05-18,English,4.5 out of 5 stars41 ratings,820.00
2,The Deep End,Writtenby:JeffKinney,Narratedby:DanRussell,2 hrs and 3 mins,06-11-20,English,4.5 out of 5 stars38 ratings,410.00
3,Daughter of the Deep,Writtenby:RickRiordan,Narratedby:SoneelaNankani,11 hrs and 16 mins,05-10-21,English,4.5 out of 5 stars12 ratings,615.00
4,"The Lightning Thief: Percy Jackson, Book 1",Writtenby:RickRiordan,Narratedby:JesseBernstein,10 hrs,13-01-10,English,4.5 out of 5 stars181 ratings,820.00

In [6]:
#Now I will make a copy of the main copy and work on that so that I can have a backup dataset if something unusual happened
df=main_copy.copy()

In [8]:
df.shape

(87489, 8)

In [7]:
df.head()

,name,author,narrator,time,releasedate,language,stars,price
0,Geronimo Stilton #11 & #12,Writtenby:GeronimoStilton,Narratedby:BillLobely,2 hrs and 20 mins,04-08-08,English,5 out of 5 stars34 ratings,468.00
1,The Burning Maze,Writtenby:RickRiordan,Narratedby:RobbieDaymond,13 hrs and 8 mins,01-05-18,English,4.5 out of 5 stars41 ratings,820.00
2,The Deep End,Writtenby:JeffKinney,Narratedby:DanRussell,2 hrs and 3 mins,06-11-20,English,4.5 out of 5 stars38 ratings,410.00
3,Daughter of the Deep,Writtenby:RickRiordan,Narratedby:SoneelaNankani,11 hrs and 16 mins,05-10-21,English,4.5 out of 5 stars12 ratings,615.00
4,"The Lightning Thief: Percy Jackson, Book 1",Writtenby:RickRiordan,Narratedby:JesseBernstein,10 hrs,13-01-10,English,4.5 out of 5 stars181 ratings,820.00

## About Dataset From Kaggle
Introduction
With the trend toward audiobooks growing, I gathered this data to understand how the audiobook market has been growing over the years. From authors of audiobooks to release dates, the data represents the important details of audiobooks from 1998 till 2025 (pre-planned releases).

I have yet to find a great audiobooks dataset and hence the urge to make a dataset that provides us with information on the basics and the history of audiobooks. I look to improve the dataset with more details in the near future.

## Column Breakdown
- **name:** Name of the audiobook
- **author:** Author of the audiobook
- **narrator:** Narrator of the audiobook
- **time:** Length of the audiobook
- **releasedate:** Release date of the audiobook
- **language:** Language of the audiobook
- **stars:** Number of stars the audiobook received
- **price:** Price of the audiobook in INR
- **ratings:** Number of reviews received by the audiobook

### Types of Assessment
There are 2 types of assessment styles

- `Manual` - Looking through the data manually in google sheets
- `Programmatic` - By using pandas functions such as info(), describe() or sample()

### Steps in Assessment
There are 2 steps involved in Assessment

- Discover
- Document

## Issues with the dataset

### 1. Dirty Data
- Every Author name is started with "writtenby:" string -> consistency
- Every Narrator is started with "Narratedby:" string -> consistency
- Time column is a string -> consistency
- Star column is a string -> consistency
- Star column has some value as "Not rated yet" with 72417 entry -> consistency
- Every column type is object -> consistency
- There is text "Narratedby:anonymous" in the Nrrator column of 1034 entry -> consistency
- There is 338 rows in price column with 'Free' value
- In the price column there is ',' in some of the price

### 2. Messy Data
-Star column has multiple values

### Automatic Assessment

- head and tail
- sample
- info
- isnull
- duplicated
- describe

In [11]:
df.head()

,name,author,narrator,time,releasedate,language,stars,price
0,Geronimo Stilton #11 & #12,Writtenby:GeronimoStilton,Narratedby:BillLobely,2 hrs and 20 mins,04-08-08,English,5 out of 5 stars34 ratings,468.00
1,The Burning Maze,Writtenby:RickRiordan,Narratedby:RobbieDaymond,13 hrs and 8 mins,01-05-18,English,4.5 out of 5 stars41 ratings,820.00
2,The Deep End,Writtenby:JeffKinney,Narratedby:DanRussell,2 hrs and 3 mins,06-11-20,English,4.5 out of 5 stars38 ratings,410.00
3,Daughter of the Deep,Writtenby:RickRiordan,Narratedby:SoneelaNankani,11 hrs and 16 mins,05-10-21,English,4.5 out of 5 stars12 ratings,615.00
4,"The Lightning Thief: Percy Jackson, Book 1",Writtenby:RickRiordan,Narratedby:JesseBernstein,10 hrs,13-01-10,English,4.5 out of 5 stars181 ratings,820.00

In [10]:
df.tail()

,name,author,narrator,time,releasedate,language,stars,price
87484,Last Days of the Bus Club,Writtenby:ChrisStewart,Narratedby:ChrisStewart,7 hrs and 34 mins,09-03-17,English,Not rated yet,596.00
87485,The Alps,Writtenby:StephenO'Shea,Narratedby:RobertFass,10 hrs and 7 mins,21-02-17,English,Not rated yet,820.00
87486,The Innocents Abroad,Writtenby:MarkTwain,Narratedby:FloGibson,19 hrs and 4 mins,30-12-16,English,Not rated yet,938.00
87487,A Sentimental Journey,Writtenby:LaurenceSterne,Narratedby:AntonLesser,4 hrs and 8 mins,23-02-11,English,Not rated yet,680.00
87488,Havana,Writtenby:MarkKurlansky,Narratedby:FleetCooper,6 hrs and 1 min,07-03-17,English,Not rated yet,569.00

In [14]:
df.sample(5)

,name,author,narrator,time,releasedate,language,stars,price
17794,Special Deluxe,Writtenby:NeilYoung,Narratedby:NeilYoung,9 hrs and 28 mins,24-09-15,English,Not rated yet,683.00
67872,Human and Alien UFO Anti-Gravity Research,Writtenby:MartinK.Ettington,Narratedby:MartinK.Ettington,2 hrs and 17 mins,18-05-21,English,Not rated yet,246.00
19548,How Not to Be a Boy,Writtenby:RobertWebb,Narratedby:RobertWebb,8 hrs and 52 mins,29-08-17,English,1 out of 5 stars1 rating,759.00
52365,"Jetzt ist gut, Knut",Writtenby:BettinaHaskamp,Narratedby:AnneWeber,4 hrs and 49 mins,31-10-21,german,Not rated yet,267.00
43056,Slug and Other Stories,Writtenby:MeganMilks,Narratedby:MeganMilks,5 hrs and 27 mins,09-11-21,English,Not rated yet,586.00

In [ ]:
# Here we can see every column type is object.
# time, releasedate, stars, price should not be object datatype, need to be changed
# and there is no null value, althoug we have null values in the stars column as string Not rated yet
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 87489 entries, 0 to 87488
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   name         87489 non-null  object
 1   author       87489 non-null  object
 2   narrator     87489 non-null  object
 3   time         87489 non-null  object
 4   releasedate  87489 non-null  object
 5   language     87489 non-null  object
 6   stars        87489 non-null  object
 7   price        87489 non-null  object
dtypes: object(8)
memory usage: 5.3+ MB

In [ ]:
# we can see here there is no null values in any of the column
df.isnull().sum()

name           0
author         0
narrator       0
time           0
releasedate    0
language       0
stars          0
price          0
dtype: int64

In [ ]:
# there is also no duplicate values
df.duplicated().sum()

0

In [35]:
#althoug there is some duplication, maybe those same books were published in different platforms
df[['name','author','narrator','time','language']].duplicated().sum()

121

In [22]:
df.describe()

,name,author,narrator,time,releasedate,language,stars,price
count,87489,87489,87489,87489,87489,87489,87489,87489
unique,82767,48374,29717,2284,5058,36,665,1011
top,The Art of War,"Writtenby:矢島雅弘,石橋遊",Narratedby:anonymous,2 mins,16-05-18,English,Not rated yet,586.00
freq,20,874,1034,372,773,61884,72417,5533

In [74]:
(df['price']=='Free').sum()

338

### Note - Assessing Data is an Iterative Process
### Data Quality Dimensions

- Completeness -> is data missing?
- Validity -> is data invalid -> negative height -> duplicate patient id
- Accuracy -> data is valid but not accurate -> weight -> 1kg
- Consistency -> both valid and accurate but written differently -> New Youk and NY
### Order of severity

Completeness <- Validity <- Accuracy <- Consistency
### Data Cleaning Order

1. Quality -> Completeness
2. Tidiness
3. Quality -> Validity
4. Quality -> Accuracy
5. Quality -> Consistency

#### Steps involved in Data cleaning
- Define
- Code
- Test

`Always make sure to create a copy of your pandas dataframe before you start the cleaning process`

In [36]:
df.head()

,name,author,narrator,time,releasedate,language,stars,price
0,Geronimo Stilton #11 & #12,Writtenby:GeronimoStilton,Narratedby:BillLobely,2 hrs and 20 mins,04-08-08,English,5 out of 5 stars34 ratings,468.00
1,The Burning Maze,Writtenby:RickRiordan,Narratedby:RobbieDaymond,13 hrs and 8 mins,01-05-18,English,4.5 out of 5 stars41 ratings,820.00
2,The Deep End,Writtenby:JeffKinney,Narratedby:DanRussell,2 hrs and 3 mins,06-11-20,English,4.5 out of 5 stars38 ratings,410.00
3,Daughter of the Deep,Writtenby:RickRiordan,Narratedby:SoneelaNankani,11 hrs and 16 mins,05-10-21,English,4.5 out of 5 stars12 ratings,615.00
4,"The Lightning Thief: Percy Jackson, Book 1",Writtenby:RickRiordan,Narratedby:JesseBernstein,10 hrs,13-01-10,English,4.5 out of 5 stars181 ratings,820.00

### We need to seperate the stars column to stars and ratings using regex

In [39]:
# Convert current stars text into separate numeric columns:
# e.g. '4.5 out of 5 stars38 ratings' -> stars_value=4.5, ratings_value=38
# Non-rated rows become stars_value=0 and ratings_value=0.


mask_not_rated = df['stars'].str.contains('Not rated yet', case=False, na=False)

# initialize with zeros
df['stars_value'] = 0.0
df['ratings_value'] = 0

# extract from valid rows (if any)
extracted = df.loc[~mask_not_rated, 'stars'].str.extract(
    r"(?P<stars_value>[0-9]+(?:\.[0-9]+)?)\s*out of\s*5\s*stars\s*(?P<ratings_value>[0-9]+)\s*ratings",
    expand=True
)

# only assign when extraction succeeds
valid = extracted['stars_value'].notna() & extracted['ratings_value'].notna()
if valid.any():
    df.loc[~mask_not_rated, 'stars_value'] = extracted.loc[valid, 'stars_value'].astype(float)
    df.loc[~mask_not_rated, 'ratings_value'] = extracted.loc[valid, 'ratings_value'].astype(int)

# clean final dtypes
df['stars_value'] = pd.to_numeric(df['stars_value'], errors='coerce').fillna(0.0).astype(float)
df['ratings_value'] = pd.to_numeric(df['ratings_value'], errors='coerce').fillna(0).astype(int)

# check result
print(df[['stars', 'stars_value', 'ratings_value']].head())

                           stars  stars_value  ratings_value
0     5 out of 5 stars34 ratings          5.0             34
1   4.5 out of 5 stars41 ratings          4.5             41
2   4.5 out of 5 stars38 ratings          4.5             38
3   4.5 out of 5 stars12 ratings          4.5             12
4  4.5 out of 5 stars181 ratings          4.5            181

In [42]:
df.drop(columns=['stars'],inplace=True)
df.head()

,name,author,narrator,time,releasedate,language,price,stars_value,ratings_value
0,Geronimo Stilton #11 & #12,Writtenby:GeronimoStilton,Narratedby:BillLobely,2 hrs and 20 mins,04-08-08,English,468.00,5.0,34
1,The Burning Maze,Writtenby:RickRiordan,Narratedby:RobbieDaymond,13 hrs and 8 mins,01-05-18,English,820.00,4.5,41
2,The Deep End,Writtenby:JeffKinney,Narratedby:DanRussell,2 hrs and 3 mins,06-11-20,English,410.00,4.5,38
3,Daughter of the Deep,Writtenby:RickRiordan,Narratedby:SoneelaNankani,11 hrs and 16 mins,05-10-21,English,615.00,4.5,12
4,"The Lightning Thief: Percy Jackson, Book 1",Writtenby:RickRiordan,Narratedby:JesseBernstein,10 hrs,13-01-10,English,820.00,4.5,181

### Fixing the author names by removing the Writtenby text from each row

In [70]:
df['author']=df['author'].str.split(":").str[1]
df.head()

,name,author,narrator,time,releasedate,language,price,stars_value,ratings_value
0,Geronimo Stilton #11 & #12,GeronimoStilton,Narratedby:BillLobely,2 hrs and 20 mins,04-08-08,English,468.00,5.0,34
1,The Burning Maze,RickRiordan,Narratedby:RobbieDaymond,13 hrs and 8 mins,01-05-18,English,820.00,4.5,41
2,The Deep End,JeffKinney,Narratedby:DanRussell,2 hrs and 3 mins,06-11-20,English,410.00,4.5,38
3,Daughter of the Deep,RickRiordan,Narratedby:SoneelaNankani,11 hrs and 16 mins,05-10-21,English,615.00,4.5,12
4,"The Lightning Thief: Percy Jackson, Book 1",RickRiordan,Narratedby:JesseBernstein,10 hrs,13-01-10,English,820.00,4.5,181

### Fixing the narrator names by removing the Narratedby text from each row

In [ ]:
df['narrator']=df['narrator'].str.split(':').str[1]
# df.drop(columns=['narrattor'],inplace=True)
df.head()

,name,author,narrator,time,releasedate,language,price,stars_value,ratings_value
0,Geronimo Stilton #11 & #12,GeronimoStilton,BillLobely,2 hrs and 20 mins,04-08-08,English,468.00,5.0,34
1,The Burning Maze,RickRiordan,RobbieDaymond,13 hrs and 8 mins,01-05-18,English,820.00,4.5,41
2,The Deep End,JeffKinney,DanRussell,2 hrs and 3 mins,06-11-20,English,410.00,4.5,38
3,Daughter of the Deep,RickRiordan,SoneelaNankani,11 hrs and 16 mins,05-10-21,English,615.00,4.5,12
4,"The Lightning Thief: Percy Jackson, Book 1",RickRiordan,JesseBernstein,10 hrs,13-01-10,English,820.00,4.5,181

### Replace the time to minutes

In [77]:
# Standardize and extract minutes from time column
# Handles formats like '2 hrs and 20 mins', '45 min', '1h 15m', '90', etc.

time_s = df['time'].astype(str).str.lower().fillna('')

# Normalize common tokens
time_s = time_s.str.replace(r'hrs?', 'hr', regex=True)
time_s = time_s.str.replace(r'hours?', 'hr', regex=True)
time_s = time_s.str.replace(r'mins?', 'min', regex=True)
time_s = time_s.str.replace(r'minutes?', 'min', regex=True)

time_s = time_s.str.replace(r'\band\b', ' ', regex=True)
time_s = time_s.str.replace(r'(?P<num>\d+)\s*h\b', r'\g<num> hr', regex=True)
time_s = time_s.str.replace(r'(?P<num>\d+)\s*m\b', r'\g<num> min', regex=True)

parts = time_s.str.extract(
    r'^\s*(?:(?P<h>\d+)\s*hr\s*)?(?:(?P<m>\d+)\s*min\s*)?$'
)

parts = parts.fillna(0).astype(int)

df['time_min'] = parts['h'] * 60 + parts['m']

# fallback 0 for any invalid/missing patterns
df['time_min'] = df['time_min'].fillna(0).astype(int)

# verify
df[['time', 'time_min']].head()

                 time  time_min
0   2 hrs and 20 mins       140
1   13 hrs and 8 mins       788
2    2 hrs and 3 mins       123
3  11 hrs and 16 mins       676
4              10 hrs       600

In [88]:
df.sample(10)

,name,author,narrator,time,releasedate,language,price,stars_value,ratings_value,time_min
24160,Living I Was Your Plague,LyndalRoper,MichaelPage,6 hrs and 45 mins,04-05-21,English,586.00,0.0,0,405
36292,Parenting a Teen Who Has Intense Emotions,"PatHarveyACSWLCSW-C,BrittH.RathboneMSSWLCSW-C",RachelPerry,7 hrs and 55 mins,16-02-21,English,586.00,0.0,0,475
36344,Build a Better Brain,PeterHollins,RussellNewton,4 hrs and 26 mins,04-02-19,English,501.00,5.0,6,266
34985,Angels in the ER,RobertLesslie,PatGrimes,7 hrs and 43 mins,05-07-21,English,"1,172.00",0.0,0,463
78784,A Creed in Stone Creek,LindaLaelMiller,JackGarrett,11 hrs and 56 mins,01-07-12,English,660.00,0.0,0,716
81162,50 Jahre Bundesliga,11FREUNDE,"PhilippKöster,JensKirschneck",1 hr and 5 mins,26-08-16,german,300.00,0.0,0,65
33878,Wounded Angels,RichardKagan,PaulBoehmer,6 hrs and 20 mins,14-09-17,English,656.00,0.0,0,380
73832,Eternal Knight,VictoriaSue,GregBoudreaux,7 hrs and 25 mins,10-08-21,English,586.00,0.0,0,445
14605,GuíaBurros: Una Guía del Museo del Prado,JavierMartín,MaríaJoséBosch,2 hrs and 39 mins,14-02-22,spanish,307.00,0.0,0,159
20323,"Cléopâtre - Une dynastie de femmes puissantes,...",Christian-GeorgesSchwentzel,Christian-GeorgesSchwentzel,3 hrs and 21 mins,03-09-21,french,793.00,0.0,0,201

In [90]:
df.drop(columns='time',inplace=True)
df.head()

,name,author,narrator,releasedate,language,price,stars_value,ratings_value,time_min
0,Geronimo Stilton #11 & #12,GeronimoStilton,BillLobely,04-08-08,English,468.00,5.0,34,140
1,The Burning Maze,RickRiordan,RobbieDaymond,01-05-18,English,820.00,4.5,41,788
2,The Deep End,JeffKinney,DanRussell,06-11-20,English,410.00,4.5,38,123
3,Daughter of the Deep,RickRiordan,SoneelaNankani,05-10-21,English,615.00,4.5,12,676
4,"The Lightning Thief: Percy Jackson, Book 1",RickRiordan,JesseBernstein,13-01-10,English,820.00,4.5,181,600

### Replace the Free text to 0 on the price column

In [93]:
df['price'].replace('Free',0,inplace=True)
(df['price']=='Free').sum()

0

### Replace the ',' from the price

In [102]:
df['price']=df['price'].str.replace(',','')
df.sample(10)

,name,author,narrator,releasedate,language,price,stars_value,ratings_value,time_min
56365,The Black Sheep and the Princess,DonnaKauffman,SebastianYork,11-11-14,English,836.00,0.0,0,671
28842,Affiliate Marketing ist das geilste Business d...,RalfSchmitz,ChristianGera,30-04-21,german,334.00,0.0,0,315
72056,Uncocky Hero,"AlexGrayson,HeroClub","TimPaige,AveryReid",26-12-21,English,668.00,0.0,0,553
62433,The Practicing Mind,ThomasM.Sterner,ThomasM.Sterner,27-12-09,English,350.00,4.5,173,231
5258,Moje pravljice 4,MihailoŠarac,div.,26-05-21,czech,200.00,0.0,0,62
76000,Saved by the Single Dad - Mitch (German edition),"WhitleyCox,RalfSchmitz-Übersetzer","VanessaStoll,PhilipDelarge",26-11-21,german,334.00,0.0,0,467
2935,Henry Ford,EmilyJames,anonymous,23-02-22,English,82.00,0.0,0,2
74990,Party of Two,JasmineGuillory,JaninaEdwards,23-06-20,English,1005.00,0.0,0,566
3838,War of 1812,ScottMarquette,uncredited,20-05-09,English,491.00,0.0,0,30
75375,Ritual,NoaXireau,EvaColl,10-09-21,spanish,345.00,0.0,0,889

### Change the releasedate column datatype

In [110]:
# Convert releasedate column to datetime
# pandas will infer the format; if needed specify format with format="%Y-%m-%d" etc.
df['releasedate'] = pd.to_datetime(df['releasedate'], errors='coerce')

df[['releasedate']].head(10)

  releasedate
0  2008-04-08
1  2018-01-05
2  2020-06-11
3  2021-05-10
4  2010-01-13
5  2018-10-30
6  2014-11-25
7  2017-02-05
8  2017-02-05
9  2019-09-24

### Changing the datatype for remaining columns

In [118]:
df['price']=df['price'].astype('float')
df['price'].dtype

dtype('float64')

In [119]:
df['stars_value']=df['stars_value'].astype('int')
df['stars_value'].dtype

dtype('int32')

In [120]:
df['ratings_value']=df['ratings_value'].astype('int')
df['ratings_value'].dtype

dtype('int32')

In [121]:
df['time_min']=df['time_min'].astype('int')
df['time_min'].dtype

dtype('int32')