In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv('smartphones.csv')

In [4]:
df.head()

,model,price,rating,sim,processor,ram,battery,display,camera,card,os
0,OnePlus 11 5G,"₹54,999",89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 100W Fast Charging,"6.7 inches, 1440 x 3216 px, 120 Hz Display wit...",50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...,Memory Card Not Supported,Android v13
1,OnePlus Nord CE 2 Lite 5G,"₹19,989",81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.59 inches, 1080 x 2412 px, 120 Hz Display wi...",64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
2,Samsung Galaxy A14 5G,"₹16,499",75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Exynos 1330, Octa Core, 2.4 GHz Processor","4 GB RAM, 64 GB inbuilt",5000 mAh Battery with 15W Fast Charging,"6.6 inches, 1080 x 2408 px, 90 Hz Display with...",50 MP + 2 MP + 2 MP Triple Rear & 13 MP Front ...,"Memory Card Supported, upto 1 TB",Android v13
3,Motorola Moto G62 5G,"₹14,999",81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.55 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
4,Realme 10 Pro Plus,"₹24,999",82.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Dimensity 1080, Octa Core, 2.6 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 67W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",108 MP + 8 MP + 2 MP Triple Rear & 16 MP Front...,Memory Card Not Supported,Android v13

## Data Assessing

### Quality Issues

1. **model** - some brands are written diiferently like OPPO in model column `consistency`
2. **price** - has unneccesary '₹' `validity`
3. **price** - has ',' between numbers `validity`
4. **price** - phone Namotel has a price of 99 `accuracy`
5. **ratings** - missing values `completeness`
6. **processor** - has some incorrect values for some samsung phones(row # -642,647,649,659,667,701,750,759,819,859,883,884,919,927,929,932,1002) `validity`
7. There is ipod on row 756 `validity`
8. **memory** - incorrect values in rows (441,485,534,553,584,610,613,642,647,649,659,667,701,750,759,819,859,884,919,927,929,932,990,1002) `validity`
9. **battery** - incorrect values in rows(113,151,309,365,378,441,450,553,584,610,613,630,642,647,649,659,667,701,750,756,759,764,819,855,859,884,915,916,927,929,932,990,1002) `validity`
10. **display** - sometimes frequency is not available `completeness`
11. **display** - incorrect values in rows(378,441,450,553,584,610,613,630,642,647,649,659,667,701,750,759,764,819,859,884,915,916,927,929,932,990,1002) `validity`
12. certain phones are foldable and the info is scattered `validity`
13. **camera** - words like Dual, Triple and Quad are used to represent number of cameras and front and rear cameras are separated by '&'
14. **camera** - problem with rows (100,113,151,157,161,238,273,308,309,323,324,365,367,378,394,441,450,484,506,534,553,571,572,575,584,610,613,615,630,642,647,649,659,667,684,687,705,711,723,728,750,756,759,764,792,819,846,854,855,858,883,884,896,915,916,927,929,932,945,956,990,995,1002,1016
) `validity`
15. **card** - sometimes contains info about os and camera `validity`
16. **os** - sometimes contains info about bluetooth and fm radio `validity`
17. **os** - issue with rows (324,378) `validity`
18. **os** - sometimes contains os version name like lollipop `consistency`
19. missing values in camera, card and os `completeness`
20. datatype  of price and rating is incorrect `validity`



### Tidiness Issues

1. **sim** - can be split into 3 cols has_5g, has_NFC, has_IR_Blaster
2. **ram** - can be split into 2 cols RAM and ROM
3. **processor** - can be split into processor name, cores and cpu speed.
4. **battery** - can be split into battery capacity, fast_charging_available
5. **display** - can be split into size, resolution_width, resolution_height and frequency
6. **camera** - can be split into front and rear camera
7. **card** - can be split into supported, extended_upto

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   model      1020 non-null   object
 1   price      1020 non-null   object
 2   rating     879 non-null    float64
 3   sim        1020 non-null   object
 4   processor  1020 non-null   object
 5   ram        1020 non-null   object
 6   battery    1020 non-null   object
 7   display    1020 non-null   object
 8   camera     1019 non-null   object
 9   card       1013 non-null   object
 10  os         1003 non-null   object
dtypes: float64(1), object(10)
memory usage: 87.8+ KB

In [6]:
df.describe()

           rating
count  879.000000
mean    78.258248
std      7.402854
min     60.000000
25%     74.000000
50%     80.000000
75%     84.000000
max     89.000000

In [7]:
df.duplicated().sum()

0

In [8]:
# make a copy
df1 = df.copy()

In [9]:
df1['price']=df1['price'].str.replace(',','').str.replace('₹','') #removing unnecessary charecters

In [10]:
df1['price']=df1['price'].astype('int')

In [11]:
df1.reset_index(inplace=True) #we have index starting from 2 in the csv file so we need a seperate indexing system to match with manual assessing indexing
df1

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
0,0,OnePlus 11 5G,54999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 100W Fast Charging,"6.7 inches, 1440 x 3216 px, 120 Hz Display wit...",50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...,Memory Card Not Supported,Android v13
1,1,OnePlus Nord CE 2 Lite 5G,19989,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.59 inches, 1080 x 2412 px, 120 Hz Display wi...",64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
2,2,Samsung Galaxy A14 5G,16499,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Exynos 1330, Octa Core, 2.4 GHz Processor","4 GB RAM, 64 GB inbuilt",5000 mAh Battery with 15W Fast Charging,"6.6 inches, 1080 x 2408 px, 90 Hz Display with...",50 MP + 2 MP + 2 MP Triple Rear & 13 MP Front ...,"Memory Card Supported, upto 1 TB",Android v13
3,3,Motorola Moto G62 5G,14999,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.55 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
4,4,Realme 10 Pro Plus,24999,82.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Dimensity 1080, Octa Core, 2.6 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 67W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",108 MP + 8 MP + 2 MP Triple Rear & 16 MP Front...,Memory Card Not Supported,Android v13
...,...,...,...,...,...,...,...,...,...,...,...,...
1015,1015,Motorola Moto Edge S30 Pro,34990,83.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 68.2W Fast Charging,"6.67 inches, 1080 x 2460 px, 120 Hz Display wi...",64 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Android v12,No FM Radio
1016,1016,Honor X8 5G,14990,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 480+, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 22.5W Fast Charging,"6.5 inches, 720 x 1600 px Display with Water D...",48 MP + 2 MP + Depth Sensor Triple Rear & 8 MP...,"Memory Card Supported, upto 1 TB",Android v11
1017,1017,POCO X4 GT 5G (8GB RAM + 256GB),28990,85.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Dimensity 8100, Octa Core, 2.85 GHz Processor","8 GB RAM, 256 GB inbuilt",5080 mAh Battery with 67W Fast Charging,"6.6 inches, 1080 x 2460 px, 144 Hz Display wit...",64 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Memory Card Not Supported,Android v12
1018,1018,Motorola Moto G91 5G,19990,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.8 inches, 1080 x 2400 px Display with Punch ...",108 MP + 8 MP + 2 MP Triple Rear & 32 MP Front...,"Memory Card Supported, upto 1 TB",Android v12
1019,1019,Samsung Galaxy M52s 5G,24990,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",Octa Core Processor,"8 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.5 inches, 1080 x 2400 px Display with Water ...",64 MP + 8 MP + 5 MP Triple Rear & 32 MP Front ...,"Memory Card Supported, upto 1 TB",Android v12

In [12]:
df1['index']=df1['index']+2 #set the new indexing colums start from 2 since it is the indexing system where we assesed the data in exel

In [13]:
processor_rows = set((642,647,649,659,667,701,750,759,819,859,883,884,919,927,929,932,1002))
ram_rows = set((441,485,534,553,584,610,613,642,647,649,659,667,701,750,759,819,859,884,919,927,929,932,990,1002))
battery_rows = set((113,151,309,365,378,441,450,553,584,610,613,630,642,647,649,659,667,701,750,756,759,764,819,855,859,884,915,916,927,929,932,990,1002))
display_rows = set((378,441,450,553,584,610,613,630,642,647,649,659,667,701,750,759,764,819,859,884,915,916,927,929,932,990,1002))
camera_rows = set((100,113,151,157,161,238,273,308,309,323,324,365,367,378,394,441,450,484,506,534,553,571,572,575,584,610,613,615,630,642,647,649,659,667,684,687,705,711,723,728,750,756,759,764,792,819,846,854,855,858,883,884,896,915,916,927,929,932,945,956,990,995,1002,1016 ))

In [14]:
df1=df1[df1['price'] >= 3400] #lower than 3400 phones are actually button phones, not smartphones, we got this info after assessing the data manually
#and got the info that any phones lower than price 3400 are not smartphone
#since the data is all about smartphones we are deleting the normal phone from the data.

In [15]:
df1[df1['index'].isin(processor_rows)]

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
645,647,Nokia 2760 Flip,5490,NaN,"Dual Sim, 3G, 4G, Wi-Fi",1450 mAh Battery,"3.6 inches, 240 x 320 px Display",5 MP Rear & 5 MP Front Camera,"Memory Card Supported, upto 32 GB",Kaios v3.0,Bluetooth,NaN
857,859,LG Folder 2,11999,NaN,"Single Sim, 3G, 4G, Wi-Fi","1 GB RAM, 8 GB inbuilt",1470 mAh Battery,"2.8 inches, 240 x 320 px Display",2 MP Rear Camera,Memory Card Supported,Bluetooth,NaN
882,884,Nokia 5710 XpressAudio,4799,NaN,"Dual Sim, 3G, 4G",No Wifi,Unisoc T107,"48 MB RAM, 128 MB inbuilt",1450 mAh Battery,"2.4 inches, 240 x 320 px Display",0.3 MP Rear Camera,"Memory Card Supported, upto 32 GB"
925,927,Nokia 3310 4G,3999,NaN,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","256 MB RAM, 512 MB inbuilt",1200 mAh Battery,"2.4 inches, 240 x 320 px Display",2 MP Rear Camera,"Memory Card Supported, upto 32 GB",Bluetooth,Browser

In [16]:
#these 4 phones are also button phones so we are removing these
df1=df1[~df1['index'].isin(processor_rows)]

In [17]:
df1[df1['index'].isin(ram_rows)]

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
439,441,Apple iPhone SE 3 2022,43900,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A15, Hexa Core, 3.22 GHz Processor",64 GB inbuilt,"4.7 inches, 750 x 1334 px Display",12 MP Rear & 7 MP Front Camera,Memory Card Not Supported,iOS v15,No FM Radio
483,485,Huawei Mate 50 RS Porsche Design,239999,81.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi, NFC, IR Blaster","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor",512 GB inbuilt,4700 mAh Battery with 66W Fast Charging,"6.74 inches, 1212 x 2616 px, 120 Hz Display",50 MP + 48 MP + 13 MP Triple Rear & 13 MP Fron...,"Memory Card (Hybrid), upto 256 GB",Hongmeng OS v3.0
582,584,Nokia 8210 4G,3749,NaN,"Dual Sim, 3G, 4G",No Wifi,Unisoc T107,"48 MB RAM, 128 MB inbuilt",1450 mAh Battery,"2.8 inches, 240 x 320 px Display",0.3 MP Rear Camera,"Memory Card Supported, upto 32 GB"

In [18]:
#there is some problem with the ram column, we will deal with it later,
#first here is a button phone, we will remove it
df1.drop(582,inplace=True)

In [19]:
df1[df1['index'].isin(battery_rows)]

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
111,113,Apple iPhone 12,51999,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 64 GB inbuilt","6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
149,151,Apple iPhone 12 Mini,40999,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 64 GB inbuilt","5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
307,309,Apple iPhone 12 (128GB),55999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 128 GB inbuilt","6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
363,365,Apple iPhone 12 Mini (128GB),45999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 128 GB inbuilt","5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
376,378,Nokia 2660 Flip,4649,NaN,"Dual Sim, 3G, 4G",No Wifi,Unisoc T107,"48 MB RAM, 128 MB inbuilt",1450 mAh Battery,"2.8 inches, 240 x 320 px Display",Dual Display,0.3 MP Rear Camera
439,441,Apple iPhone SE 3 2022,43900,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A15, Hexa Core, 3.22 GHz Processor",64 GB inbuilt,"4.7 inches, 750 x 1334 px Display",12 MP Rear & 7 MP Front Camera,Memory Card Not Supported,iOS v15,No FM Radio
448,450,Apple iPhone 15 Pro,130990,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",Bionic A16,"8 GB RAM, 128 GB inbuilt","6.06 inches, 1170 x 2532 px, 120 Hz Display wi...",50 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v15,No FM Radio
628,630,Apple iPhone 12 Pro (512GB),139900,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","6 GB RAM, 512 GB inbuilt","6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v14.0,No FM Radio
754,756,Apple iPod Touch (7th Gen),18900,NaN,Wi-Fi,32 GB inbuilt,"4 inches, 640 x 1136 px Display",8 MP Rear & 1.2 MP Front Camera,iOS v12,No FM Radio,Bluetooth,Browser
762,764,Apple iPhone SE 4,49990,60.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A15, Hexa Core, 3.22 GHz Processor",64 GB inbuilt,"6.1 inches, 750 x 1580 px Display",12 MP Rear & 10.8 MP Front Camera,Memory Card Not Supported,iOS v16,No FM Radio
853,855,Apple iPhone 12 Pro (256GB),119900,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","6 GB RAM, 256 GB inbuilt","6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v14.0,No FM Radio
913,915,Apple iPhone 12 Mini (256GB),55999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 256 GB inbuilt","5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
914,916,Apple iPhone 12 (256GB),67999,76.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 256 GB inbuilt","6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio

In [20]:
df1.drop([376,754],inplace=True) #these 2 also are button phone

In [21]:
#shifting the values to it's correct column
df1.loc[df1['index'].isin(battery_rows),['battery','display','camera','card','os']]=df1.loc[df1['index'].isin(battery_rows),['battery','display','camera','card','os']].shift(1,axis=1)
df1[df1['index'].isin(battery_rows)]

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
111,113,Apple iPhone 12,51999,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 64 GB inbuilt",None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
149,151,Apple iPhone 12 Mini,40999,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 64 GB inbuilt",None,"5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
307,309,Apple iPhone 12 (128GB),55999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 128 GB inbuilt",None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
363,365,Apple iPhone 12 Mini (128GB),45999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 128 GB inbuilt",None,"5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
439,441,Apple iPhone SE 3 2022,43900,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A15, Hexa Core, 3.22 GHz Processor",64 GB inbuilt,None,"4.7 inches, 750 x 1334 px Display",12 MP Rear & 7 MP Front Camera,Memory Card Not Supported,iOS v15
448,450,Apple iPhone 15 Pro,130990,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",Bionic A16,"8 GB RAM, 128 GB inbuilt",None,"6.06 inches, 1170 x 2532 px, 120 Hz Display wi...",50 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v15
628,630,Apple iPhone 12 Pro (512GB),139900,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","6 GB RAM, 512 GB inbuilt",None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v14.0
762,764,Apple iPhone SE 4,49990,60.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A15, Hexa Core, 3.22 GHz Processor",64 GB inbuilt,None,"6.1 inches, 750 x 1580 px Display",12 MP Rear & 10.8 MP Front Camera,Memory Card Not Supported,iOS v16
853,855,Apple iPhone 12 Pro (256GB),119900,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","6 GB RAM, 256 GB inbuilt",None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v14.0
913,915,Apple iPhone 12 Mini (256GB),55999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 256 GB inbuilt",None,"5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
914,916,Apple iPhone 12 (256GB),67999,76.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 256 GB inbuilt",None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14

In [22]:
df1[df1['index'].isin(display_rows)]
#here we can see, the display problem is already solved after solving the battery porblem, cause the problem was same, position problem

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
439,441,Apple iPhone SE 3 2022,43900,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A15, Hexa Core, 3.22 GHz Processor",64 GB inbuilt,None,"4.7 inches, 750 x 1334 px Display",12 MP Rear & 7 MP Front Camera,Memory Card Not Supported,iOS v15
448,450,Apple iPhone 15 Pro,130990,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",Bionic A16,"8 GB RAM, 128 GB inbuilt",None,"6.06 inches, 1170 x 2532 px, 120 Hz Display wi...",50 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v15
628,630,Apple iPhone 12 Pro (512GB),139900,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","6 GB RAM, 512 GB inbuilt",None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v14.0
762,764,Apple iPhone SE 4,49990,60.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A15, Hexa Core, 3.22 GHz Processor",64 GB inbuilt,None,"6.1 inches, 750 x 1580 px Display",12 MP Rear & 10.8 MP Front Camera,Memory Card Not Supported,iOS v16
913,915,Apple iPhone 12 Mini (256GB),55999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 256 GB inbuilt",None,"5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
914,916,Apple iPhone 12 (256GB),67999,76.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 256 GB inbuilt",None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14

In [23]:
temp_df=df1[df1['index'].isin(camera_rows)]
#there are some of the rows in the camera column, the actural info of camera is shifted to card column, so we need to retrieve those values back

In [24]:
ind=temp_df[~temp_df['camera'].str.contains('MP')].index #getting the index of those values that we don't have the camera info.

In [25]:
df1.loc[ind,'camera']=df1.loc[ind,'card'] #getting the info from the card collumn for those rows

In [26]:
df1[df1['index'].isin(camera_rows)]
#we cann see the camera row problems are solved

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
98,100,Vivo X Fold 5G,106990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","12 GB RAM, 256 GB inbuilt",4600 mAh Battery with 66W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display",50 MP Quad Rear & 16 MP Front Camera,50 MP Quad Rear & 16 MP Front Camera,Android v12
111,113,Apple iPhone 12,51999,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 64 GB inbuilt",None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
149,151,Apple iPhone 12 Mini,40999,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 64 GB inbuilt",None,"5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
155,157,Nokia 2780 Flip,4990,NaN,"Dual Sim, 3G, 4G, Wi-Fi","Snapdragon QM215, Quad Core, 1.3 GHz Processor","4 GB RAM, 512 MB inbuilt",1450 mAh Battery,"2.7 inches, 240 x 320 px Display",5 MP Rear Camera,5 MP Rear Camera,"Memory Card Supported, upto 32 GB"
159,161,Oppo Find N2 5G,94990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4520 mAh Battery with 67W Fast Charging,"7.1 inches, 1792 x 1920 px, 120 Hz Display wit...",50 MP + 48 MP + 32 MP Triple Rear & 32 MP + 32...,50 MP + 48 MP + 32 MP Triple Rear & 32 MP + 32...,Memory Card Not Supported
236,238,Xiaomi Mix Fold 2 5G,106990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 8+ Gen1 , Octa Core, 3.2 GHz Proce...","12 GB RAM, 256 GB inbuilt",4500 mAh Battery with 67W Fast Charging,"8.02 inches, 1914 x 2160 px, 120 Hz Display wi...",50 MP + 13 MP + 8 MP Triple Rear & 20 MP Front...,50 MP + 13 MP + 8 MP Triple Rear & 20 MP Front...,Android v12
271,273,Nokia 2720 V Flip,6199,NaN,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Snapdragon 205 , Dual Core, 1.1 GHz Processor","512 MB RAM, 4 GB inbuilt",1500 mAh Battery,"2.8 inches, 240 x 320 px Display",2 MP Rear Camera,2 MP Rear Camera,Memory Card Supported
306,308,Samsung Galaxy Z Flip 3,69999,84.0,"Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",3300 mAh Battery with 15W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...",12 MP + 12 MP Dual Rear & 10 MP Front Camera,12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
307,309,Apple iPhone 12 (128GB),55999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 128 GB inbuilt",None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
321,323,Samsung Galaxy Z Fold 4,154998,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1812 x 2176 px, 120 Hz Display wit...",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v12
322,324,Royole FlexPai 2,109999,87.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 865, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",4450 mAh Battery,"7.8 inches, 1440 x 1920 px Display",64 MP + 16 MP + 8 MP Triple Rear & 32 MP Front...,64 MP + 16 MP + 8 MP Triple Rear & 32 MP Front...,"Memory Card Supported, upto 256 GB"
363,365,Apple iPhone 12 Mini (128GB),45999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 128 GB inbuilt",None,"5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
365,367,OPPO Find N Flip,89990,88.0,"Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000, Octa Core, 3.05 GHz Processor","8 GB RAM, 128 GB inbuilt",4300 mAh Battery with 44W Fast Charging,"6.8 inches, 1200 x 2400 px, 120 Hz Display wit...",50 MP + 8 MP Dual Rear & 32 MP Front Camera,50 MP + 8 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
392,394,OPPO Find N2 Flip,70990,88.0,"Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000 Plus, Octa Core, 3.2 GHz Processor","8 GB RAM, 256 GB inbuilt",4300 mAh Battery with 44W Fast Charging,"6.8 inches, 1080 x 2520 px, 120 Hz Display wit...",50 MP + 8 MP Dual Rear & 32 MP Front Camera,50 MP + 8 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
439,441,Apple iPhone SE 3 2022,43900,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A15, Hexa Core, 3.22 GHz Processor",64 GB inbuilt,None,"4.7 inches, 750 x 1334 px Display",12 MP Rear & 7 MP Front Camera,Memory Card Not Supported,iOS v15
448,450,Apple iPhone 15 Pro,130990,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",Bionic A16,"8 GB RAM, 128 GB inbuilt",None,"6.06 inches, 1170 x 2532 px, 120 Hz Display wi...",50 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v15
482,484,Vivo X Fold Plus,113990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4730 mAh Battery with 80W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display wi...",50 MP Quad Rear & 16 MP + 16 MP Dual Front Camera,50 MP Quad Rear & 16 MP + 16 MP Dual Front Camera,Android v12
504,506,Samsung Galaxy Z Flip 4 5G,89999,88.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","8 GB RAM, 128 GB inbuilt",3700 mAh Battery with 25W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...",12 MP + 12 MP Dual Rear & 10 MP Front Camera,12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
569,571,Samsung Galaxy Z Fold 3,110999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 888, Octa Core, 2.84 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1768 x 2208 px, 120 Hz Display wit...",12 MP + 12 MP + 12 MP Triple Rear & 10 MP + 4 ...,12 MP + 12 MP + 12 MP Triple Rear & 10 MP + 4 ...,Android v11
570,572,LG Wing 5G,54999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 765G , Octa Core, 2.4 GHz Processor","8 GB RAM, 128 GB inbuilt",4000 mAh Battery with Fast Charging,"6.8 inches, 1080 x 2460 px Display",64 MP + 13 MP + 12 MP Triple Rear & 32 MP Fron...,64 MP + 13 MP + 12 MP Triple Rear & 32 MP Fron...,"Memory Card (Hybrid), upto 2 TB"
613,615,Oukitel WP21,22990,82.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Helio G99, Octa Core, 2.2 GHz Processor","12 GB RAM, 256 GB inbuilt",9800 mAh Battery with 66W Fast Charging,"6.78 inches, 1080 x 2400 px, 120 Hz Display",64 MP + 20 MP + 2 MP Triple Rear & Main Front ...,64 MP + 20 MP + 2 MP Triple Rear & Main Front ...,Memory Card (Hybrid)
628,630,Apple iPhone 12 Pro (512GB),139900,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","6 GB RAM, 512 GB inbuilt",None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v14.0
682,684,LG V60 ThinQ,79990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 865, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.8 inches, 1080 x 2460 px Display with Punch ...",64 MP + 13 MP + 0.3 MP Triple Rear & 10 MP Fro...,64 MP + 13 MP + 0.3 MP Triple Rear & 10 MP Fro...,"Memory Card (Hybrid), upto 2 TB"
703,705,Oppo Find N 5G,92249,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 256 GB inbuilt",4500 mAh Battery with 33W Fast Charging,"7.1 inches, 1792 x 1920 px, 120 Hz Display wit...",50 MP + 16 MP + 13 MP Triple Rear & 32 MP Fron...,50 MP + 16 MP + 13 MP Triple Rear & 32 MP Fron...,Android v11
709,711,OPPO X 2021,134999,86.0,"Single Sim, 3G, 4G, VoLTE, Wi-Fi","Snapdragon 865, Octa Core, 2.84 GHz Processor","8 GB RAM, 256 GB inbuilt",4000 mAh Battery with 45W Fast Charging,"7.4 inches, 1440 x 3200 px Display",64 MP + 16 MP + 12 MP Triple Rear & 16 MP Fron...,64 MP + 16 MP + 12 MP Triple Rear & 16 MP Fron...,Android v11
721,723,Asus ROG Phone 6D Ultimate,107990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000 Plus, Octa Core, 3.2 GHz Processor","16 GB RAM, 512 GB inbuilt",6000 mAh Battery with 65W Fast Charging,"6.78 inches, 1080 x 2448 px, 165 Hz Display",50 MP + 13 MP + 5 MP Triple Rear & 12 MP Front...,50 MP + 13 MP + 5 MP Triple Rear & 12 MP Front...,Memory Card Not Supported
726,728,Huawei Mate Xs 2,162990,89.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi, NFC, IR Blaster","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 512 GB inbuilt",4600 mAh Battery with 66W Fast Charging,"7.8 inches, 2200 x 2480 px, 120 Hz Display wit...",50 MP + 13 MP + 8 MP Triple Rear & 10.7 MP Fro...,50 MP + 13 MP + 8 MP Triple Rear & 10.7 MP Fro...,"Memory Card (Hybrid), upto 256 GB"
762,764,Apple iPhone SE 4,49990,60.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A15, Hexa Core, 3.22 GHz Processor",64 GB inbuilt,None,"6.1 inches, 750 x 1580 px Display",12 MP Rear & 10.8 MP Front Camera,Memory Card Not Supported,iOS v16
790,792,Xiaomi Mi Mix Fold,109990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 888 , Octa Core, 2.84 GHz Processor","12 GB RAM, 256 GB inbuilt",5020 mAh Battery with 67W Fast Charging,"8.01 inches, 1860 x 2480 px, 90 Hz Display",108 MP + 13 MP + 8 MP Triple Rear & 20 MP Fron...,108 MP + 13 MP + 8 MP Triple Rear & 20 MP Fron...,Android v10
844,846,CAT S22 Flip,14999,NaN,"Single Sim, 3G, 4G, VoLTE, Wi-Fi","Qualcomm 215, Quad Core, 1.3 GHz Processor","2 GB RAM, 16 GB inbuilt",2000 mAh Battery,"4 inches, 480 x 640 px Display",5 MP Rear & 2 MP Front Camera,5 MP Rear & 2 MP Front Camera,"Memory Card Supported, upto 128 GB"
853,855,Apple iPhone 12 Pro (256GB),119900,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","6 GB RAM, 256 GB inbuilt",None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v14.0
856,858,Samsung Galaxy A01 Core,4999,NaN,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","(28 nm), Quad Core, 1.5 GHz Processor","1 GB RAM, 16 GB inbuilt",3000 mAh Battery,"5.3 inches, 720 x 1480 px Display",8 MP Rear & 5 MP Front Camera,Memory Card Supported,Android v10
894,896,Royole FlexPai 3 5G,149999,87.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",3360 mAh Battery,"7.2 inches, 1440 x 1920 px Display",64 MP + 16 MP + 8 MP Triple Rear & 32 MP Front...,64 MP + 16 MP + 8 MP Triple Rear & 32 MP Front...,"Memory Card Supported, upto 256 GB"
913,915,Apple iPhone 12 Mini (256GB),55999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 256 GB inbuilt",None,"5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
914,916,Apple iPhone 12 (256GB),67999,76.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 256 GB inbuilt",None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
943,945,Samsung Galaxy Z Fold 4 (12GB RAM + 1TB),163980,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 1 TB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1812 x 2176 px, 120 Hz Display wit...",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v12
954,956,Vivo X Fold 5G (12GB RAM + 512GB),118990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","12 GB RAM, 512 GB inbuilt",4600 mAh Battery with 66W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display",50 MP Quad Rear & 16 MP Front Camera,50 MP Quad Rear & 16 MP Front Camera,Android v12
993,995,Huawei Mate X,169000,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Kirin 990, Octa Core, 2.86 GHz Processor","8 GB RAM, 512 GB inbuilt",4500 mAh Battery with 55W Fast Charging,"8 inches, 2200 x 2480 px Display",48 MP Quad Rear Camera,48 MP Quad Rear Camera,"Memory Card (Hybrid), upto 256 GB"
1014,1016,Vivo X Fold 2,119990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4800 mAh Battery with 66W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display",50 MP + 50 MP + 10 MP Triple Rear & 32 MP Fron...,50 MP + 50 MP + 10 MP Triple Rear & 32 MP Fron...,Android v12

In [27]:
df1['camera'].value_counts()

camera
50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front Camera           40
64 MP + 8 MP + 2 MP Triple Rear & 16 MP Front Camera           38
50 MP + 2 MP + 2 MP Triple Rear & 16 MP Front Camera           34
13 MP + 2 MP Dual Rear & 5 MP Front Camera                     23
13 MP Rear & 5 MP Front Camera                                 20
                                                               ..
48 MP + 8 MP + 5 MP Triple Rear & 8 MP Front Camera             1
20 MP + 16 MP Dual Rear & 16 MP Front Camera                    1
108 MP + 50 MP + 48 MP Triple Rear & 32 MP Front Camera         1
64 MP + 64 MP + 64 MP Triple Rear & 16 MP Front Camera          1
48 MP + 2 MP + Depth Sensor Triple Rear & 8 MP Front Camera     1
Name: count, Length: 286, dtype: int64

In [28]:
df1['card'].value_counts().reset_index()
#there are some issues with the card collumn let's fix them

                                                 card  count
0                    Memory Card Supported, upto 1 TB    171
1                           Memory Card Not Supported    123
2                                         Android v12    107
3                  Memory Card Supported, upto 512 GB    105
4                     Memory Card (Hybrid), upto 1 TB     91
5                               Memory Card Supported     89
6                  Memory Card Supported, upto 256 GB     87
7                                         Android v13     46
8                                         Android v11     41
9                                Memory Card (Hybrid)     30
10                  Memory Card (Hybrid), upto 256 GB     13
11                  Memory Card (Hybrid), upto 512 GB     11
12                                        Android v10     11
13                 Memory Card Supported, upto 128 GB      6
14                   Memory Card Supported, upto 2 TB      5
15                  Memory Card Supported, upto 32 GB      4
16                   Memory Card (Hybrid), upto 64 GB      3
17                  Memory Card (Hybrid), upto 128 GB      3
18                                 Android v9.0 (Pie)      2
19        50 MP + 8 MP Dual Rear & 32 MP Front Camera      2
20  50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...      2
21  64 MP + 16 MP + 8 MP Triple Rear & 32 MP Front...      2
22       12 MP + 12 MP Dual Rear & 10 MP Front Camera      2
23               50 MP Quad Rear & 16 MP Front Camera      2
24                                            iOS v13      1
25                      5 MP Rear & 2 MP Front Camera      1
26                    Memory Card (Hybrid), upto 2 TB      1
27                                          HarmonyOS      1
28  108 MP + 13 MP + 8 MP Triple Rear & 20 MP Fron...      1
29                             48 MP Quad Rear Camera      1
30                                     HarmonyOS v2.0      1
31  50 MP + 13 MP + 8 MP Triple Rear & 10.7 MP Fro...      1
32  50 MP + 13 MP + 5 MP Triple Rear & 12 MP Front...      1
33  64 MP + 16 MP + 12 MP Triple Rear & 16 MP Fron...      1
34  50 MP + 16 MP + 13 MP Triple Rear & 32 MP Fron...      1
35  64 MP + 13 MP + 0.3 MP Triple Rear & 10 MP Fro...      1
36                Memory Card Supported, upto 1000 GB      1
37                                      Android v10.0      1
38  64 MP + 20 MP + 2 MP Triple Rear & Main Front ...      1
39                                            iOS v10      1
40  64 MP + 13 MP + 12 MP Triple Rear & 32 MP Fron...      1
41  12 MP + 12 MP + 12 MP Triple Rear & 10 MP + 4 ...      1
42                                   5 MP Rear Camera      1
43  50 MP Quad Rear & 16 MP + 16 MP Dual Front Camera      1
44                                      Android v12.1      1
45  64 MP + 10 MP + 8 MP Triple Rear & 32 MP Front...      1
46                                   2 MP Rear Camera      1
47  50 MP + 13 MP + 8 MP Triple Rear & 20 MP Front...      1
48  50 MP + 48 MP + 32 MP Triple Rear & 32 MP + 32...      1
49  50 MP + 50 MP + 10 MP Triple Rear & 32 MP Fron...      1

In [29]:
df1[df1['os'].str.contains('Card')]
#here we can see, there are some rows where we have the card values in the os column
#let's just use left shift here to retrieve the values, and we don't have the info for the os columns for these rows

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
155,157,Nokia 2780 Flip,4990,NaN,"Dual Sim, 3G, 4G, Wi-Fi","Snapdragon QM215, Quad Core, 1.3 GHz Processor","4 GB RAM, 512 MB inbuilt",1450 mAh Battery,"2.7 inches, 240 x 320 px Display",5 MP Rear Camera,5 MP Rear Camera,"Memory Card Supported, upto 32 GB"
159,161,Oppo Find N2 5G,94990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4520 mAh Battery with 67W Fast Charging,"7.1 inches, 1792 x 1920 px, 120 Hz Display wit...",50 MP + 48 MP + 32 MP Triple Rear & 32 MP + 32...,50 MP + 48 MP + 32 MP Triple Rear & 32 MP + 32...,Memory Card Not Supported
271,273,Nokia 2720 V Flip,6199,NaN,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Snapdragon 205 , Dual Core, 1.1 GHz Processor","512 MB RAM, 4 GB inbuilt",1500 mAh Battery,"2.8 inches, 240 x 320 px Display",2 MP Rear Camera,2 MP Rear Camera,Memory Card Supported
306,308,Samsung Galaxy Z Flip 3,69999,84.0,"Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",3300 mAh Battery with 15W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...",12 MP + 12 MP Dual Rear & 10 MP Front Camera,12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
322,324,Royole FlexPai 2,109999,87.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 865, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",4450 mAh Battery,"7.8 inches, 1440 x 1920 px Display",64 MP + 16 MP + 8 MP Triple Rear & 32 MP Front...,64 MP + 16 MP + 8 MP Triple Rear & 32 MP Front...,"Memory Card Supported, upto 256 GB"
365,367,OPPO Find N Flip,89990,88.0,"Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000, Octa Core, 3.05 GHz Processor","8 GB RAM, 128 GB inbuilt",4300 mAh Battery with 44W Fast Charging,"6.8 inches, 1200 x 2400 px, 120 Hz Display wit...",50 MP + 8 MP Dual Rear & 32 MP Front Camera,50 MP + 8 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
392,394,OPPO Find N2 Flip,70990,88.0,"Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000 Plus, Octa Core, 3.2 GHz Processor","8 GB RAM, 256 GB inbuilt",4300 mAh Battery with 44W Fast Charging,"6.8 inches, 1080 x 2520 px, 120 Hz Display wit...",50 MP + 8 MP Dual Rear & 32 MP Front Camera,50 MP + 8 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
504,506,Samsung Galaxy Z Flip 4 5G,89999,88.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","8 GB RAM, 128 GB inbuilt",3700 mAh Battery with 25W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...",12 MP + 12 MP Dual Rear & 10 MP Front Camera,12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
570,572,LG Wing 5G,54999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 765G , Octa Core, 2.4 GHz Processor","8 GB RAM, 128 GB inbuilt",4000 mAh Battery with Fast Charging,"6.8 inches, 1080 x 2460 px Display",64 MP + 13 MP + 12 MP Triple Rear & 32 MP Fron...,64 MP + 13 MP + 12 MP Triple Rear & 32 MP Fron...,"Memory Card (Hybrid), upto 2 TB"
613,615,Oukitel WP21,22990,82.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Helio G99, Octa Core, 2.2 GHz Processor","12 GB RAM, 256 GB inbuilt",9800 mAh Battery with 66W Fast Charging,"6.78 inches, 1080 x 2400 px, 120 Hz Display",64 MP + 20 MP + 2 MP Triple Rear & Main Front ...,64 MP + 20 MP + 2 MP Triple Rear & Main Front ...,Memory Card (Hybrid)
682,684,LG V60 ThinQ,79990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 865, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.8 inches, 1080 x 2460 px Display with Punch ...",64 MP + 13 MP + 0.3 MP Triple Rear & 10 MP Fro...,64 MP + 13 MP + 0.3 MP Triple Rear & 10 MP Fro...,"Memory Card (Hybrid), upto 2 TB"
721,723,Asus ROG Phone 6D Ultimate,107990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000 Plus, Octa Core, 3.2 GHz Processor","16 GB RAM, 512 GB inbuilt",6000 mAh Battery with 65W Fast Charging,"6.78 inches, 1080 x 2448 px, 165 Hz Display",50 MP + 13 MP + 5 MP Triple Rear & 12 MP Front...,50 MP + 13 MP + 5 MP Triple Rear & 12 MP Front...,Memory Card Not Supported
726,728,Huawei Mate Xs 2,162990,89.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi, NFC, IR Blaster","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 512 GB inbuilt",4600 mAh Battery with 66W Fast Charging,"7.8 inches, 2200 x 2480 px, 120 Hz Display wit...",50 MP + 13 MP + 8 MP Triple Rear & 10.7 MP Fro...,50 MP + 13 MP + 8 MP Triple Rear & 10.7 MP Fro...,"Memory Card (Hybrid), upto 256 GB"
844,846,CAT S22 Flip,14999,NaN,"Single Sim, 3G, 4G, VoLTE, Wi-Fi","Qualcomm 215, Quad Core, 1.3 GHz Processor","2 GB RAM, 16 GB inbuilt",2000 mAh Battery,"4 inches, 480 x 640 px Display",5 MP Rear & 2 MP Front Camera,5 MP Rear & 2 MP Front Camera,"Memory Card Supported, upto 128 GB"
894,896,Royole FlexPai 3 5G,149999,87.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",3360 mAh Battery,"7.2 inches, 1440 x 1920 px Display",64 MP + 16 MP + 8 MP Triple Rear & 32 MP Front...,64 MP + 16 MP + 8 MP Triple Rear & 32 MP Front...,"Memory Card Supported, upto 256 GB"
993,995,Huawei Mate X,169000,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Kirin 990, Octa Core, 2.86 GHz Processor","8 GB RAM, 512 GB inbuilt",4500 mAh Battery with 55W Fast Charging,"8 inches, 2200 x 2480 px Display",48 MP Quad Rear Camera,48 MP Quad Rear Camera,"Memory Card (Hybrid), upto 256 GB"

In [30]:
idx=df1[df1['os'].str.contains('Card')].index #getting the index

In [31]:
df1.loc[idx,['card','os']]=df1.loc[idx,['card','os']].shift(-1,axis=1) #left shift

In [32]:
df1['card'].value_counts().reset_index()

                                                 card  count
0                    Memory Card Supported, upto 1 TB    171
1                           Memory Card Not Supported    129
2                                         Android v12    107
3                  Memory Card Supported, upto 512 GB    105
4                     Memory Card (Hybrid), upto 1 TB     91
5                               Memory Card Supported     90
6                  Memory Card Supported, upto 256 GB     89
7                                         Android v13     46
8                                         Android v11     41
9                                Memory Card (Hybrid)     31
10                  Memory Card (Hybrid), upto 256 GB     15
11                                        Android v10     11
12                  Memory Card (Hybrid), upto 512 GB     11
13                 Memory Card Supported, upto 128 GB      7
14                   Memory Card Supported, upto 2 TB      5
15                  Memory Card Supported, upto 32 GB      5
16                  Memory Card (Hybrid), upto 128 GB      3
17                   Memory Card (Hybrid), upto 64 GB      3
18                    Memory Card (Hybrid), upto 2 TB      3
19               50 MP Quad Rear & 16 MP Front Camera      2
20  50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...      2
21                                 Android v9.0 (Pie)      2
22                                      Android v10.0      1
23                                          HarmonyOS      1
24  108 MP + 13 MP + 8 MP Triple Rear & 20 MP Fron...      1
25                                     HarmonyOS v2.0      1
26  64 MP + 16 MP + 12 MP Triple Rear & 16 MP Fron...      1
27  50 MP + 16 MP + 13 MP Triple Rear & 32 MP Fron...      1
28                                            iOS v13      1
29                Memory Card Supported, upto 1000 GB      1
30                                            iOS v10      1
31  12 MP + 12 MP + 12 MP Triple Rear & 10 MP + 4 ...      1
32  50 MP Quad Rear & 16 MP + 16 MP Dual Front Camera      1
33                                      Android v12.1      1
34  64 MP + 10 MP + 8 MP Triple Rear & 32 MP Front...      1
35  50 MP + 13 MP + 8 MP Triple Rear & 20 MP Front...      1
36  50 MP + 50 MP + 10 MP Triple Rear & 32 MP Fron...      1

In [33]:
df1[df1['card'].str.contains('MP')]

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
69,71,Oppo Find N Fold,99990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","8 GB RAM, 256 GB inbuilt",5000 mAh Battery with 67W Fast Charging,"7.1 inches, 1792 x 1920 px, 120 Hz Display wit...","Foldable Display, Dual Display",64 MP + 10 MP + 8 MP Triple Rear & 32 MP Front...,Android v12
98,100,Vivo X Fold 5G,106990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","12 GB RAM, 256 GB inbuilt",4600 mAh Battery with 66W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display",50 MP Quad Rear & 16 MP Front Camera,50 MP Quad Rear & 16 MP Front Camera,Android v12
236,238,Xiaomi Mix Fold 2 5G,106990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 8+ Gen1 , Octa Core, 3.2 GHz Proce...","12 GB RAM, 256 GB inbuilt",4500 mAh Battery with 67W Fast Charging,"8.02 inches, 1914 x 2160 px, 120 Hz Display wi...",50 MP + 13 MP + 8 MP Triple Rear & 20 MP Front...,50 MP + 13 MP + 8 MP Triple Rear & 20 MP Front...,Android v12
321,323,Samsung Galaxy Z Fold 4,154998,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1812 x 2176 px, 120 Hz Display wit...",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v12
482,484,Vivo X Fold Plus,113990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4730 mAh Battery with 80W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display wi...",50 MP Quad Rear & 16 MP + 16 MP Dual Front Camera,50 MP Quad Rear & 16 MP + 16 MP Dual Front Camera,Android v12
569,571,Samsung Galaxy Z Fold 3,110999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 888, Octa Core, 2.84 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1768 x 2208 px, 120 Hz Display wit...",12 MP + 12 MP + 12 MP Triple Rear & 10 MP + 4 ...,12 MP + 12 MP + 12 MP Triple Rear & 10 MP + 4 ...,Android v11
703,705,Oppo Find N 5G,92249,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 256 GB inbuilt",4500 mAh Battery with 33W Fast Charging,"7.1 inches, 1792 x 1920 px, 120 Hz Display wit...",50 MP + 16 MP + 13 MP Triple Rear & 32 MP Fron...,50 MP + 16 MP + 13 MP Triple Rear & 32 MP Fron...,Android v11
709,711,OPPO X 2021,134999,86.0,"Single Sim, 3G, 4G, VoLTE, Wi-Fi","Snapdragon 865, Octa Core, 2.84 GHz Processor","8 GB RAM, 256 GB inbuilt",4000 mAh Battery with 45W Fast Charging,"7.4 inches, 1440 x 3200 px Display",64 MP + 16 MP + 12 MP Triple Rear & 16 MP Fron...,64 MP + 16 MP + 12 MP Triple Rear & 16 MP Fron...,Android v11
790,792,Xiaomi Mi Mix Fold,109990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 888 , Octa Core, 2.84 GHz Processor","12 GB RAM, 256 GB inbuilt",5020 mAh Battery with 67W Fast Charging,"8.01 inches, 1860 x 2480 px, 90 Hz Display",108 MP + 13 MP + 8 MP Triple Rear & 20 MP Fron...,108 MP + 13 MP + 8 MP Triple Rear & 20 MP Fron...,Android v10
943,945,Samsung Galaxy Z Fold 4 (12GB RAM + 1TB),163980,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 1 TB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1812 x 2176 px, 120 Hz Display wit...",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v12
954,956,Vivo X Fold 5G (12GB RAM + 512GB),118990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","12 GB RAM, 512 GB inbuilt",4600 mAh Battery with 66W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display",50 MP Quad Rear & 16 MP Front Camera,50 MP Quad Rear & 16 MP Front Camera,Android v12
1014,1016,Vivo X Fold 2,119990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4800 mAh Battery with 66W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display",50 MP + 50 MP + 10 MP Triple Rear & 32 MP Fron...,50 MP + 50 MP + 10 MP Triple Rear & 32 MP Fron...,Android v12

In [34]:
# here we can see we missed a camera problem, let's just solve the camera problem first, then move forward
df1['camera'].value_counts().to_string()
# so there is only one row that has different value, Foldable Display, Dual Display 1 and the index is 69, let's fix it

'camera\n50\u2009MP + 8\u2009MP + 2\u2009MP Triple Rear & 16\u2009MP Front Camera                   40\n64\u2009MP + 8\u2009MP + 2\u2009MP Triple Rear & 16\u2009MP Front Camera                   38\n50\u2009MP + 2\u2009MP + 2\u2009MP Triple Rear & 16\u2009MP Front Camera                   34\n13\u2009MP + 2\u2009MP Dual Rear & 5\u2009MP Front Camera                             23\n13\u2009MP Rear & 5\u2009MP Front Camera                                         20\n50\u2009MP + 2\u2009MP + 2\u2009MP Triple Rear & 8\u2009MP Front Camera                    20\n12\u2009MP + 12\u2009MP Dual Rear & 12\u2009MP Front Camera                           20\n8\u2009MP Rear & 5\u2009MP Front Camera                                          19\n50\u2009MP + 2\u2009MP Dual Rear & 8\u2009MP Front Camera                             19\n13\u2009MP + 2\u2009MP Dual Rear & 8\u2009MP Front Camera                             18\n108\u2009MP + 8\u2009MP + 2\u2009MP Triple Rear & 16\u2009MP Front Camera                  18\n64\u2009MP Quad Rear & 32\u2009MP Front Camera                                   18\n64\u2009MP + 2\u2009MP + 2\u2009MP Triple Rear & 16\u2009MP Front Camera                   16\n50\u2009MP + 2\u2009MP Dual Rear & 5\u2009MP Front Camera                             14\n48\u2009MP + 2\u2009MP + 2\u2009MP Triple Rear & 16\u2009MP Front Camera                   14\n48\u2009MP Quad Rear & 13\u2009MP Front Camera                                   14\n50\u2009MP Quad Rear & 8\u2009MP Front Camera                                    13\n108\u2009MP Quad Rear & 32\u2009MP Front Camera                                  12\n48\u2009MP Quad Rear & 16\u2009MP Front Camera                                   12\n50\u2009MP + 8\u2009MP + 2\u2009MP Triple Rear & 32\u2009MP Front Camera                   11\n12\u2009MP + 12\u2009MP + 12\u2009MP Triple Rear & 12\u2009MP Front Camera                 10\n108\u2009MP Quad Rear & 16\u2009MP Front Camera                                  10\n13\u2009MP + 2\u2009MP + 2\u2009MP Triple Rear & 5\u2009MP Front Camera                    10\n64\u2009MP Quad Rear & 16\u2009MP Front Camera                                   10\n64\u2009MP + 8\u2009MP + 2\u2009MP Triple Rear & 32\u2009MP Front Camera                   10\n13\u2009MP + 2\u2009MP + 2\u2009MP Triple Rear & 8\u2009MP Front Camera                     9\n13\u2009MP Dual Rear & 8\u2009MP Front Camera                                     9\n50\u2009MP + 8\u2009MP Dual Rear & 16\u2009MP Front Camera                             9\n48\u2009MP + 2\u2009MP + 2\u2009MP Triple Rear & 8\u2009MP Front Camera                     8\n48\u2009MP + 12\u2009MP + 12\u2009MP Triple Rear & 12\u2009MP Front Camera                  8\n8\u2009MP Dual Rear & 5\u2009MP Front Camera                                      8\n64\u2009MP Quad Rear & 20\u2009MP Front Camera                                    8\n50\u2009MP + 13\u2009MP + 2\u2009MP Triple Rear & 32\u2009MP Front Camera                   7\n50\u2009MP + 2\u2009MP Triple Rear & 16\u2009MP Front Camera                           7\n50\u2009MP Dual Rear & 8\u2009MP Front Camera                                     7\n50\u2009MP + 2\u2009MP Dual Rear & 16\u2009MP Front Camera                             6\n50\u2009MP Quad Rear & 16\u2009MP Front Camera                                    6\n50\u2009MP + 50\u2009MP + 50\u2009MP Triple Rear & 32\u2009MP Front Camera                  6\n48\u2009MP + 8\u2009MP + 2\u2009MP Triple Rear & 16\u2009MP Front Camera                    6\n108\u2009MP Quad Rear & 40\u2009MP Front Camera                                   6\n50\u2009MP + 2\u2009MP Triple Rear & 8\u2009MP Front Camera                            6\n48\u2009MP Quad Rear & 8\u2009MP Front Camera                                     6\n50\u2009MP Quad Rear & 32\u2009MP Front Camera                                    5\n64\u2009MP + 12\u2009MP + 12\u2009MP Triple Rear & 10\u2009MP Front Camera                  5\n50\u2009MP + 5\u2009MP + 2\u2009MP Triple Rear & 8\u2009MP Front Camera                     5\n50\u2009MP + 50\u2009MP + 2\u2009MP Triple Rear & 32\u2009MP Front Camera                   5\n13\u2009MP + 2\u2009MP + 2\u2009MP Triple Rear & 16\u2009MP Front Camera                    5\n64\u2009MP + 8\u2009MP + 5\u2009MP Triple Rear & 32\u2009MP Front Camera                    5\n64\u2009MP + 2\u2009MP + 2\u2009MP Triple Rear & 32\u2009MP Front Camera                    5\n64\u2009MP + 8\u2009MP + 2\u2009MP Triple Rear & 20\u2009MP Front Camera                    5\n108\u2009MP + 8\u2009MP + 2\u2009MP Triple Rear & 32\u2009MP Front Camera                   5\n12\u2009MP + 12\u2009MP + 8\u2009MP Triple Rear & 32\u2009MP Front Camera                   5\n200\u2009MP + 8\u2009MP + 2\u2009MP Triple Rear & 16\u2009MP Front Camera                   5\n48\u2009MP + 13\u2009MP + 2\u2009MP Triple Rear & 16\u2009MP Front Camera                   4\n50\u2009MP + 12\u2009MP + 10\u2009MP Triple Rear & 10\u2009MP Front Camera                  4\n64\u2009MP + 8\u2009MP + 2\u2009MP Triple Rear & 50\u2009MP Front Camera                    4\n50\u2009MP + 2\u2009MP + 2\u2009MP Triple Rear & 5\u2009MP Front Camera                     4\n108\u2009MP + 2\u2009MP Dual Rear & 16\u2009MP Front Camera                            4\n5\u2009MP Rear & 2\u2009MP Front Camera                                           4\n50\u2009MP + 8\u2009MP Dual Rear & 32\u2009MP Front Camera                             4\n50\u2009MP Quad Rear & 13\u2009MP Front Camera                                    4\n13\u2009MP Rear & 8\u2009MP Front Camera                                          4\n64\u2009MP Quad Rear & 13\u2009MP Front Camera                                    4\n64\u2009MP + 8\u2009MP + 2\u2009MP Triple Rear & 44\u2009MP Front Camera                    4\n50\u2009MP + 13\u2009MP + 5\u2009MP Triple Rear & 12\u2009MP Front Camera                   4\n200\u2009MP + 50\u2009MP + 12\u2009MP Triple Rear & 60\u2009MP Front Camera                 4\n50\u2009MP + 50\u2009MP Dual Rear & 16\u2009MP Front Camera                            3\n50\u2009MP + 12\u2009MP + 5\u2009MP Triple Rear & 32\u2009MP Front Camera                   3\n50\u2009MP + 8\u2009MP + 2\u2009MP Triple Rear & 13\u2009MP Front Camera                    3\n48\u2009MP + 2\u2009MP Dual Rear & 5\u2009MP Front Camera                              3\n12\u2009MP Rear & 7\u2009MP Front Camera                                          3\n48\u2009MP + 8\u2009MP + 5\u2009MP Triple Rear & 20\u2009MP Front Camera                    3\n50\u2009MP + 8\u2009MP + 2\u2009MP Triple Rear & 8\u2009MP Front Camera                     3\n50\u2009MP + 2\u2009MP + 2\u2009MP Triple Rear & 13\u2009MP Front Camera                    3\n8\u2009MP + Depth Sensor Dual Rear & 5\u2009MP Front Camera                       3\n48\u2009MP + 8\u2009MP + 2\u2009MP Triple Rear & 13\u2009MP Front Camera                    3\n64\u2009MP + 16\u2009MP + 8\u2009MP Triple Rear & 32\u2009MP Front Camera                   3\n50\u2009MP + 12\u2009MP + 12\u2009MP Triple Rear & 32\u2009MP Front Camera                  3\n108\u2009MP + 13\u2009MP + 2\u2009MP Triple Rear & 16\u2009MP Front Camera                  3\n16\u2009MP + 8\u2009MP + 2\u2009MP Triple Rear & 16\u2009MP Front Camera                    3\n48\u2009MP + 13\u2009MP + 13\u2009MP Triple Rear & 16\u2009MP Front Camera                  3\n8\u2009MP + 0.3\u2009MP Dual Rear & 5\u2009MP Front Camera                             3\n2\u2009MP Rear Camera                                                        3\n16\u2009MP + 2\u2009MP Dual Rear & 8\u2009MP Front Camera                              3\n50\u2009MP + 48\u2009MP + 8\u2009MP Triple Rear & 32\u2009MP Front Camera                   3\n50\u2009MP + Depth Sensor Dual Rear & 8\u2009MP Front Camera                      3\n48\u2009MP + 2\u2009MP Dual Rear & 8\u2009MP Front Camera                              3\n48\u2009MP + 8\u2009MP + 2\u2009MP Triple Rear & 8\u2009MP Front Camera                     3\n12\u2009MP + 8\u2009MP + 8\u2009MP Triple Rear & 8\u2009MP Front Camera                     2\n12\u2009MP + 12\u2009MP + 12\u2009MP Triple Rear & 8\u2009MP Front Camera                   2\n64\u2009MP Quad Rear & 32\u2009MP + 8\u2009MP Dual Front Camera                        2\n54\u2009MP + 50\u2009MP + 2\u2009MP Triple Rear & 32\u2009MP Front Camera                   2\n108\u2009MP + 8\u2009MP + 5\u2009MP Triple Rear & 16\u2009MP Front Camera                   2\n50\u2009MP + 48\u2009MP + 32\u2009MP Triple Rear & 16\u2009MP Front Camera                  2\n48\u2009MP + 2\u2009MP Dual Rear & 16\u2009MP Front Camera                             2\n64\u2009MP + 5\u2009MP + 2\u2009MP Triple Rear & 8\u2009MP Front Camera                     2\n48\u2009MP + 8\u2009MP + 5\u2009MP Triple Rear & 16\u2009MP Front Camera                    2\n8\u2009MP + 0.08\u2009MP Dual Rear & 5\u2009MP Front Camera                            2\n48\u2009MP + 8\u2009MP + 5\u2009MP Triple Rear & 32\u2009MP Front Camera                    2\n108\u2009MP + 13\u2009MP + 2\u2009MP Triple Rear & 32\u2009MP Front Camera                  2\n108\u2009MP + 8\u2009MP + 2\u2009MP Triple Rear & 20\u2009MP Front Camera                   2\n64\u2009MP Quad Rear & 16\u2009MP + 8\u2009MP Dual Front Camera                        2\n48\u2009MP + 8\u2009MP + 2\u2009MP Triple Rear & 20\u2009MP Front Camera                    2\n50\u2009MP + 12\u2009MP + 10\u2009MP Triple Rear & 10\u2009MP + 4\u2009MP Dual Front Camera      2\n16\u2009MP + 12.2\u2009MP Dual Rear & 8\u2009MP Front Camera                           2\n12.2\u2009MP Rear & 8\u2009MP Front Camera                                        2\n64\u2009MP + 50\u2009MP + 2\u2009MP Triple Rear & 32\u2009MP Front Camera                   2\n16\u2009MP + 2\u2009MP + 2\u2009MP Triple Rear & 8\u2009MP Front Camera                     2\n64\u2009MP + 8\u2009MP + 2\u2009MP Triple Rear & 8\u2009MP Front Camera                     2\n13\u2009MP + 8\u2009MP + 2\u2009MP Triple Rear & 16\u2009MP Front Camera                    2\n12\u2009MP + 5\u2009MP Dual Rear & 20\u2009MP Front Camera                             2\n64\u2009MP + 12\u2009MP + 5\u2009MP Triple Rear & 10\u2009MP Front Camera                   2\n64\u2009MP Quad Rear & 10\u2009MP Front Camera                                    2\n16\u2009MP + 5\u2009MP Dual Rear & 25\u2009MP Front Camera                             2\n13\u2009MP + 5\u2009MP + 2\u2009MP Triple Rear & 8\u2009MP Front Camera                     2\n50\u2009MP + Depth Sensor Dual Rear & 5\u2009MP Front Camera                      2\n20\u2009MP Rear & 13\u2009MP Front Camera                                         2\n50\u2009MP + 5\u2009MP + 2\u2009MP Triple Rear & 16\u2009MP Front Camera                    2\n12\u2009MP Quad Rear & 10\u2009MP Front Camera                                    2\n108\u2009MP + 2\u2009MP + 2\u2009MP Triple Rear & 16\u2009MP Front Camera                   2\n12.2\u2009MP + 12\u2009MP Dual Rear & 8\u2009MP Front Camera                           2\n8\u2009MP + 2\u2009MP + 0.3\u2009MP Triple Rear & 8\u2009MP Front Camera                    2\n50\u2009MP + 50\u2009MP + 12\u2009MP Triple Rear & 60\u2009MP Front Camera                  2\n50\u2009MP + 13\u2009MP + 8\u2009MP Triple Rear & 16\u2009MP Front Camera                   2\n64\u2009MP + 12\u2009MP + 5\u2009MP Triple Rear & 32\u2009MP Front Camera                   2\n13\u2009MP Dual Rear & 5\u2009MP Front Camera                                     2\n64\u2009MP + 8\u2009MP + 2\u2009MP Triple Rear & 50\u2009MP + 8\u2009MP Dual Front Camera        2\n108\u2009MP + 8\u2009MP + 2\u2009MP Triple Rear & 50\u2009MP + 8\u2009MP Dual Front Camera       2\n50\u2009MP + 12\u2009MP + 12\u2009MP Triple Rear & 12\u2009MP Front Camera                  2\n50\u2009MP + 12\u2009MP + 10\u2009MP Triple Rear & 12\u2009MP Front Camera                  2\n50\u2009MP + 50\u2009MP + 13\u2009MP Triple Rear & 32\u2009MP Front Camera                  2\n50\u2009MP + 0.3\u2009MP Dual Rear & 5\u2009MP Front Camera                            2\n50\u2009MP + 8\u2009MP + 2\u2009MP Triple Rear & 44\u2009MP Front Camera                    2\n12\u2009MP + 12\u2009MP Dual Rear & 10\u2009MP Front Camera                            2\n64\u2009MP + 8\u2009MP + 5\u2009MP Triple Rear & 20\u2009MP Front Camera                    2\n50\u2009MP + 48\u2009MP + 12\u2009MP Triple Rear & 11.1\u2009MP Front Camera                2\n50\u2009MP + 50\u2009MP + 10\u2009MP Triple Rear & 32\u2009MP Front Camera                  1\n40\u2009MP Quad Rear & 32\u2009MP Dual Front Camera                               1\n64\u2009MP + 50\u2009MP + 8\u2009MP Triple Rear & 16\u2009MP Front Camera                   1\n48\u2009MP Quad Rear Camera                                                  1\n24\u2009MP + 10\u2009MP + 5\u2009MP Triple Rear & 24\u2009MP Front Camera                   1\n50\u2009MP + 8\u2009MP + 2\u2009MP Triple Rear & 20\u2009MP Front Camera                    1\n24\u2009MP + 8\u2009MP + 5\u2009MP Triple Rear & 24\u2009MP Front Camera                    1\n50\u2009MP + 16\u2009MP + 13\u2009MP Triple Rear & 32\u2009MP Front Camera                  1\n108\u2009MP + 64\u2009MP + 16\u2009MP Triple Rear & 32\u2009MP Front Camera                 1\n13\u2009MP + 8\u2009MP + 2\u2009MP Triple Rear & 8\u2009MP Front Camera                     1\n64\u2009MP + 16\u2009MP + 12\u2009MP Triple Rear & 16\u2009MP Front Camera                  1\n50\u2009MP + 50\u2009MP + 50\u2009MP Triple Rear & 12\u2009MP Front Camera                  1\n48\u2009MP Quad Rear & 32\u2009MP + 8\u2009MP Dual Front Camera                        1\n48\u2009MP Quad Rear & 32\u2009MP Front Camera                                    1\n16\u2009MP + 13\u2009MP + 13\u2009MP Triple Rear & 8\u2009MP Front Camera                   1\n108\u2009MP + 13\u2009MP + 5\u2009MP Triple Rear & 20\u2009MP Front Camera                  1\n64\u2009MP + 8\u2009MP + 2\u2009MP Triple Rear & 44\u2009MP + 8\u2009MP Dual Front Camera        1\n50\u2009MP + 13\u2009MP + 2\u2009MP Triple Rear & 32\u2009MP + 16\u2009MP Dual Front Camera      1\n16\u2009MP Rear & 13\u2009MP Front Camera                                         1\n5\u2009MP Rear & 5\u2009MP Front Camera                                           1\n5\u2009MP + 0.3\u2009MP Dual Rear & 5\u2009MP Front Camera                             1\n13\u2009MP Quad Rear & 8\u2009MP Front Camera                                     1\n50\u2009MP + 48\u2009MP + 32\u2009MP Triple Rear & 32\u2009MP Front Camera                  1\n48\u2009MP Quad Rear & 16\u2009MP + 2\u2009MP Dual Front Camera                        1\n50\u2009MP + 13\u2009MP Dual Rear & 13\u2009MP Front Camera                            1\n50\u2009MP + 13\u2009MP + 8\u2009MP Triple Rear & 10.7\u2009MP Front Camera                 1\n64\u2009MP + 50\u2009MP + 13\u2009MP Triple Rear & 13\u2009MP Front Camera                  1\n64\u2009MP + 20\u2009MP + 2\u2009MP Triple Rear & 32\u2009MP + 32\u2009MP Dual Front Camera      1\n64\u2009MP + 13\u2009MP Dual Rear & 32\u2009MP Front Camera                            1\n200\u2009MP + 50\u2009MP + 8\u2009MP Triple Rear & 50\u2009MP Front Camera                  1\n50\u2009MP + 2\u2009MP Triple Rear & 5\u2009MP Front Camera                            1\n48\u2009MP + 12.2\u2009MP + 12.2\u2009MP Triple Rear & 16\u2009MP Front Camera              1\n64\u2009MP + 16\u2009MP Dual Rear & 20\u2009MP Front Camera                            1\n12\u2009MP + 12\u2009MP + 12\u2009MP Triple Rear & 32\u2009MP Front Camera                  1\n48\u2009MP + 2\u2009MP Triple Rear & 32\u2009MP Front Camera                           1\n50\u2009MP + 3\u2009MP + 2\u2009MP Triple Rear & 8\u2009MP Front Camera                     1\n50\u2009MP + 13\u2009MP + 5\u2009MP Triple Rear & 32\u2009MP Front Camera                   1\n50\u2009MP Quad Rear & 48\u2009MP + 8\u2009MP Dual Front Camera                        1\n64\u2009MP + 8\u2009MP + 5\u2009MP Triple Rear & 16\u2009MP Front Camera                    1\n108\u2009MP + 8\u2009MP + 5\u2009MP Triple Rear & 20\u2009MP Front Camera                   1\n12\u2009MP + 2\u2009MP + 2\u2009MP Triple Rear & 8\u2009MP Front Camera                     1\n12\u2009MP Rear & 10.8\u2009MP Front Camera                                       1\n48\u2009MP + 12\u2009MP + 5\u2009MP Triple Rear & 16\u2009MP Front Camera                   1\n50\u2009MP + 8\u2009MP + 2\u2009MP Triple Rear & 60\u2009MP Front Camera                    1\n12\u2009MP + 2\u2009MP Dual Rear & 8\u2009MP Front Camera                              1\n16\u2009MP + 12\u2009MP + 12\u2009MP Triple Rear & 10\u2009MP Front Camera                  1\n13\u2009MP + 2\u2009MP Dual Rear & 16\u2009MP Front Camera                             1\n50\u2009MP + 13\u2009MP Dual Rear & 16\u2009MP Front Camera                            1\n108\u2009MP + 20\u2009MP + 16\u2009MP Triple Rear & 32\u2009MP Front Camera                 1\n48\u2009MP + 13\u2009MP + 8\u2009MP Triple Rear & 20\u2009MP Front Camera                   1\n13\u2009MP Rear & 16\u2009MP Front Camera                                         1\n13\u2009MP Rear & 13\u2009MP Front Camera                                         1\n13\u2009MP + 2\u2009MP Triple Rear & 8\u2009MP Front Camera                            1\n64\u2009MP + 16\u2009MP + 2\u2009MP Triple Rear & 16\u2009MP Front Camera                   1\n50\u2009MP + 8\u2009MP Dual Rear & 10.1\u2009MP Front Camera                           1\n108\u2009MP + 13\u2009MP + 8\u2009MP Triple Rear & 20\u2009MP Front Camera                  1\n13\u2009MP + 2\u2009MP Dual Rear & 13\u2009MP Front Camera                             1\n108\u2009MP Quad Rear & 20\u2009MP Front Camera                                   1\n50\u2009MP Quad Rear & 32\u2009MP Dual Front Camera                               1\n13\u2009MP + 2\u2009MP Dual Rear & 20\u2009MP Front Camera                             1\n48\u2009MP + 8\u2009MP + 2\u2009MP Triple Rear & 32\u2009MP Front Camera                    1\n12\u2009MP + 12\u2009MP Dual Rear & 8\u2009MP Front Camera                             1\n200\u2009MP Quad Rear & 16\u2009MP Front Camera                                   1\n47.2\u2009MP + 1.9\u2009MP Dual Rear & 12.6\u2009MP Front Camera                       1\n64\u2009MP + 2\u2009MP Dual Rear & 16\u2009MP Front Camera                             1\n50\u2009MP + 50\u2009MP Triple Rear & 16\u2009MP Front Camera                          1\n50\u2009MP + 12\u2009MP Dual Rear & 16\u2009MP Front Camera                            1\n50\u2009MP + 20\u2009MP + 2\u2009MP Triple Rear & 32\u2009MP + 32\u2009MP Dual Front Camera      1\n50\u2009MP + 50\u2009MP + 50\u2009MP Triple Rear & 20\u2009MP Front Camera                  1\n50\u2009MP + 48\u2009MP + 48\u2009MP Triple Rear & 32\u2009MP Front Camera                  1\n64\u2009MP + 13\u2009MP + 0.3\u2009MP Triple Rear & 10\u2009MP Front Camera                 1\n64\u2009MP + 13\u2009MP + 5\u2009MP Triple Rear & 20\u2009MP Front Camera                   1\n50\u2009MP + 50\u2009MP + 13\u2009MP Triple Rear & 16\u2009MP Front Camera                  1\n50\u2009MP + 13\u2009MP + 8\u2009MP Triple Rear & 20\u2009MP Front Camera                   1\n50\u2009MP + 12\u2009MP Dual Rear & 10.8\u2009MP Front Camera                          1\n108\u2009MP + 13\u2009MP + 2\u2009MP Triple Rear & 60\u2009MP Front Camera                  1\n12\u2009MP + 5\u2009MP Dual Rear & 7\u2009MP Front Camera                              1\n108\u2009MP + 2\u2009MP Triple Rear & 16\u2009MP Front Camera                          1\n50\u2009MP + 12\u2009MP + 10\u2009MP Triple Rear & 32\u2009MP Front Camera                  1\n50\u2009MP + 16\u2009MP + 2\u2009MP Triple Rear & 16\u2009MP Front Camera                   1\n50\u2009MP + 8\u2009MP + 2\u2009MP Triple Rear & 50\u2009MP + 8\u2009MP Dual Front Camera        1\n50\u2009MP + 12\u2009MP Du

In [35]:
df1.loc[69,'camera']=df1.loc[69,'card'] #solved

In [36]:
df1[df1['card'].str.contains('MP')]

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
69,71,Oppo Find N Fold,99990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","8 GB RAM, 256 GB inbuilt",5000 mAh Battery with 67W Fast Charging,"7.1 inches, 1792 x 1920 px, 120 Hz Display wit...",64 MP + 10 MP + 8 MP Triple Rear & 32 MP Front...,64 MP + 10 MP + 8 MP Triple Rear & 32 MP Front...,Android v12
98,100,Vivo X Fold 5G,106990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","12 GB RAM, 256 GB inbuilt",4600 mAh Battery with 66W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display",50 MP Quad Rear & 16 MP Front Camera,50 MP Quad Rear & 16 MP Front Camera,Android v12
236,238,Xiaomi Mix Fold 2 5G,106990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 8+ Gen1 , Octa Core, 3.2 GHz Proce...","12 GB RAM, 256 GB inbuilt",4500 mAh Battery with 67W Fast Charging,"8.02 inches, 1914 x 2160 px, 120 Hz Display wi...",50 MP + 13 MP + 8 MP Triple Rear & 20 MP Front...,50 MP + 13 MP + 8 MP Triple Rear & 20 MP Front...,Android v12
321,323,Samsung Galaxy Z Fold 4,154998,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1812 x 2176 px, 120 Hz Display wit...",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v12
482,484,Vivo X Fold Plus,113990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4730 mAh Battery with 80W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display wi...",50 MP Quad Rear & 16 MP + 16 MP Dual Front Camera,50 MP Quad Rear & 16 MP + 16 MP Dual Front Camera,Android v12
569,571,Samsung Galaxy Z Fold 3,110999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 888, Octa Core, 2.84 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1768 x 2208 px, 120 Hz Display wit...",12 MP + 12 MP + 12 MP Triple Rear & 10 MP + 4 ...,12 MP + 12 MP + 12 MP Triple Rear & 10 MP + 4 ...,Android v11
703,705,Oppo Find N 5G,92249,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 256 GB inbuilt",4500 mAh Battery with 33W Fast Charging,"7.1 inches, 1792 x 1920 px, 120 Hz Display wit...",50 MP + 16 MP + 13 MP Triple Rear & 32 MP Fron...,50 MP + 16 MP + 13 MP Triple Rear & 32 MP Fron...,Android v11
709,711,OPPO X 2021,134999,86.0,"Single Sim, 3G, 4G, VoLTE, Wi-Fi","Snapdragon 865, Octa Core, 2.84 GHz Processor","8 GB RAM, 256 GB inbuilt",4000 mAh Battery with 45W Fast Charging,"7.4 inches, 1440 x 3200 px Display",64 MP + 16 MP + 12 MP Triple Rear & 16 MP Fron...,64 MP + 16 MP + 12 MP Triple Rear & 16 MP Fron...,Android v11
790,792,Xiaomi Mi Mix Fold,109990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 888 , Octa Core, 2.84 GHz Processor","12 GB RAM, 256 GB inbuilt",5020 mAh Battery with 67W Fast Charging,"8.01 inches, 1860 x 2480 px, 90 Hz Display",108 MP + 13 MP + 8 MP Triple Rear & 20 MP Fron...,108 MP + 13 MP + 8 MP Triple Rear & 20 MP Fron...,Android v10
943,945,Samsung Galaxy Z Fold 4 (12GB RAM + 1TB),163980,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 1 TB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1812 x 2176 px, 120 Hz Display wit...",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v12
954,956,Vivo X Fold 5G (12GB RAM + 512GB),118990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","12 GB RAM, 512 GB inbuilt",4600 mAh Battery with 66W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display",50 MP Quad Rear & 16 MP Front Camera,50 MP Quad Rear & 16 MP Front Camera,Android v12
1014,1016,Vivo X Fold 2,119990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4800 mAh Battery with 66W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display",50 MP + 50 MP + 10 MP Triple Rear & 32 MP Fron...,50 MP + 50 MP + 10 MP Triple Rear & 32 MP Fron...,Android v12

In [37]:
#in these rows, there is no card info available, so let's replace the values with none
idx=df1[df1['card'].str.contains('MP')].index
df1.loc[idx,'card']=None

In [38]:
df1['card'].value_counts().reset_index()

                                   card  count
0      Memory Card Supported, upto 1 TB    171
1             Memory Card Not Supported    129
2                           Android v12    107
3    Memory Card Supported, upto 512 GB    105
4       Memory Card (Hybrid), upto 1 TB     91
5                 Memory Card Supported     90
6    Memory Card Supported, upto 256 GB     89
7                           Android v13     46
8                           Android v11     41
9                  Memory Card (Hybrid)     31
10    Memory Card (Hybrid), upto 256 GB     15
11    Memory Card (Hybrid), upto 512 GB     11
12                          Android v10     11
13   Memory Card Supported, upto 128 GB      7
14    Memory Card Supported, upto 32 GB      5
15     Memory Card Supported, upto 2 TB      5
16    Memory Card (Hybrid), upto 128 GB      3
17     Memory Card (Hybrid), upto 64 GB      3
18      Memory Card (Hybrid), upto 2 TB      3
19                   Android v9.0 (Pie)      2
20                        Android v12.1      1
21  Memory Card Supported, upto 1000 GB      1
22                              iOS v10      1
23                        Android v10.0      1
24                              iOS v13      1
25                       HarmonyOS v2.0      1
26                            HarmonyOS      1

In [39]:
#now let's deal with the android
# with pd.option_context('display.max_rows', None):
#     print(df1[df1['card'].str.contains('Android',na=False)])
temp_df=df1[df1['card'].str.contains('Android',na=False)]

In [40]:
with pd.option_context('display.max_rows',None):

    print(temp_df[['card','os']])

                    card           os
8            Android v12  No FM Radio
9            Android v12  No FM Radio
12           Android v12  No FM Radio
17           Android v13  No FM Radio
18           Android v12    Bluetooth
20           Android v13    Bluetooth
21           Android v12  No FM Radio
24           Android v13  No FM Radio
29           Android v13  No FM Radio
37           Android v12    Bluetooth
39           Android v13  No FM Radio
51           Android v13  No FM Radio
58           Android v13  No FM Radio
60           Android v12    Bluetooth
61           Android v13  No FM Radio
65           Android v13  No FM Radio
66           Android v12  No FM Radio
73           Android v12  No FM Radio
85           Android v12  No FM Radio
91           Android v12  No FM Radio
93           Android v13  No FM Radio
97           Android v13  No FM Radio
102          Android v12  No FM Radio
106          Android v13  No FM Radio
107          Android v12    Bluetooth
109          Android v12    Bluetooth
110          Android v12  No FM Radio
112          Android v12    Bluetooth
115          Android v12  No FM Radio
119          Android v13  No FM Radio
120          Android v12  No FM Radio
121          Android v12  No FM Radio
133          Android v12  No FM Radio
139          Android v12  No FM Radio
141          Android v13  No FM Radio
146          Android v11  No FM Radio
163          Android v13  No FM Radio
168          Android v12  No FM Radio
170          Android v11  No FM Radio
183          Android v13  No FM Radio
186          Android v11  No FM Radio
189          Android v11  No FM Radio
196          Android v12  No FM Radio
202          Android v12  No FM Radio
203          Android v12  No FM Radio
206          Android v12  No FM Radio
209          Android v12  No FM Radio
211          Android v12  No FM Radio
215          Android v12  No FM Radio
216          Android v13  No FM Radio
220          Android v13  No FM Radio
223          Android v12  No FM Radio
228          Android v12  No FM Radio
229          Android v12  No FM Radio
230          Android v12  No FM Radio
231          Android v13  No FM Radio
244          Android v13  No FM Radio
249          Android v13  No FM Radio
251          Android v12    Bluetooth
257          Android v12    Bluetooth
258          Android v11  No FM Radio
267          Android v13  No FM Radio
269          Android v13  No FM Radio
272          Android v12  No FM Radio
276          Android v12  No FM Radio
286          Android v12  No FM Radio
296          Android v12  No FM Radio
298          Android v13  No FM Radio
301          Android v12    Bluetooth
308          Android v12  No FM Radio
311          Android v11  No FM Radio
313          Android v12    Bluetooth
319          Android v11    Bluetooth
320          Android v13  No FM Radio
326          Android v12  No FM Radio
328          Android v10  No FM Radio
335          Android v12  No FM Radio
342          Android v12    Bluetooth
347          Android v13  No FM Radio
354          Android v13  No FM Radio
359          Android v12  No FM Radio
361          Android v12  No FM Radio
362          Android v12  No FM Radio
366          Android v12  No FM Radio
371          Android v11  No FM Radio
379          Android v12  No FM Radio
380          Android v10  No FM Radio
383          Android v11  No FM Radio
399   Android v9.0 (Pie)    Bluetooth
401          Android v13  No FM Radio
415          Android v11  No FM Radio
422          Android v12  No FM Radio
423          Android v12  No FM Radio
424          Android v12  No FM Radio
425        Android v12.1  No FM Radio
428          Android v11  No FM Radio
434          Android v12  No FM Radio
453          Android v11    Bluetooth
456          Android v12  No FM Radio
458          Android v12  No FM Radio
463          Android v13  No FM Radio
464          Android v13  No FM Radio
493          Android v12  No FM Radio
495          Android v12  No FM Radio
500          Android v11  No FM Radio
508          Android v12  No FM Radio
515          Android v11    Bluetooth
516          Android v13  No FM Radio
519          Android v12  No FM Radio
525          Android v11  No FM Radio
526          Android v12    Bluetooth
534          Android v12    Bluetooth
535          Android v12  No FM Radio
540          Android v12  No FM Radio
541          Android v12  No FM Radio
544          Android v12    Bluetooth
545          Android v12  No FM Radio
554          Android v11  No FM Radio
557          Android v12  No FM Radio
559          Android v12  No FM Radio
561          Android v13  No FM Radio
565          Android v11  No FM Radio
566          Android v11  No FM Radio
568          Android v13  No FM Radio
579          Android v13  No FM Radio
583          Android v12  No FM Radio
584          Android v12  No FM Radio
591          Android v12  No FM Radio
594          Android v12  No FM Radio
615          Android v12  No FM Radio
630        Android v10.0  No FM Radio
631          Android v10  No FM Radio
633          Android v12  No FM Radio
634          Android v12  No FM Radio
637          Android v12  No FM Radio
638          Android v12    Bluetooth
641          Android v12    Bluetooth
643          Android v11  No FM Radio
644          Android v11    Bluetooth
652          Android v11  No FM Radio
658          Android v11  No FM Radio
659          Android v13  No FM Radio
669          Android v12  No FM Radio
676          Android v11  No FM Radio
679          Android v10  No FM Radio
686          Android v13  No FM Radio
700          Android v12  No FM Radio
722          Android v12  No FM Radio
723          Android v12  No FM Radio
732          Android v11  No FM Radio
737          Android v12  No FM Radio
740          Android v11  No FM Radio
742          Android v11  No FM Radio
745          Android v10  No FM Radio
746          Android v10  No FM Radio
759          Android v13  No FM Radio
760          Android v13  No FM Radio
761          Android v12  No FM Radio
765          Android v13  No FM Radio
766          Android v12  No FM Radio
768          Android v12  No FM Radio
769          Android v12  No FM Radio
770          Android v12    Bluetooth
772          Android v11  No FM Radio
774          Android v12    Bluetooth
777          Android v12  No FM Radio
785          Android v12  No FM Radio
796          Android v10  No FM Radio
806          Android v13  No FM Radio
810          Android v13    Bluetooth
812          Android v12  No FM Radio
820          Android v12    Bluetooth
822          Android v12  No FM Radio
836          Android v11    Bluetooth
842          Android v11  No FM Radio
843          Android v12  No FM Radio
848          Android v11  No FM Radio
849          Android v10  No FM Radio
851          Android v10  No FM Radio
858          Android v11    Bluetooth
868   Android v9.0 (Pie)  No FM Radio
888          Android v12  No FM Radio
890          Android v12  No FM Radio
891          Android v12  No FM Radio
895          Android v11    Bluetooth
896          Android v11    Bluetooth
898          Android v11  No FM Radio
907          Android v10  No FM Radio
908          Android v10  No FM Radio
909          Android v11    Bluetooth
933          Android v13    Bluetooth
934          Android v12  No FM Radio
941          Android v12  No FM Radio
944          Android v12  No FM Radio
945          Android v12  No FM Radio
946          Android v12  No FM Radio
947          Android v12    Bluetooth
962          Android v11  No FM Radio
967          Android v11  No FM Radio
971          Android v11  No FM Radio
974          Android v11  No FM Radio
975          Android v11  No FM Radio
1007         Android v13  No FM Radio
1008         Android v13  No FM Radio
1009         Android v13  No FM Radio
1011         Android v12  No FM Radio
1012         Android v11  No FM Radio
1013         Android v13  No FM Radio
1015         Android v12  No FM Radio

In [41]:
# we can shift those values on card that contains os info to os column
idx=temp_df.index
df1.loc[idx,['card','os']]=df1.loc[idx,['card','os']].shift(1,axis=1) #right shift

In [42]:
df1['card'].value_counts().reset_index()

                                   card  count
0      Memory Card Supported, upto 1 TB    171
1             Memory Card Not Supported    129
2    Memory Card Supported, upto 512 GB    105
3       Memory Card (Hybrid), upto 1 TB     91
4                 Memory Card Supported     90
5    Memory Card Supported, upto 256 GB     89
6                  Memory Card (Hybrid)     31
7     Memory Card (Hybrid), upto 256 GB     15
8     Memory Card (Hybrid), upto 512 GB     11
9    Memory Card Supported, upto 128 GB      7
10    Memory Card Supported, upto 32 GB      5
11     Memory Card Supported, upto 2 TB      5
12    Memory Card (Hybrid), upto 128 GB      3
13     Memory Card (Hybrid), upto 64 GB      3
14      Memory Card (Hybrid), upto 2 TB      3
15  Memory Card Supported, upto 1000 GB      1
16                              iOS v10      1
17                              iOS v13      1
18                       HarmonyOS v2.0      1
19                            HarmonyOS      1

In [43]:
#now do the same for ios and harmony os
temp_df=df1[df1['card'].str.contains('iOS|Harmony',na=False)]

In [44]:
temp_df
#i need to right sift to shift them to os column

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
607,609,Apple iPhone 7s,52990,NaN,"Single Sim, 3G, 4G, VoLTE, Wi-Fi","Fusion APL1024, Quad Core, 2.37 GHz Processor","3 GB RAM, 32 GB inbuilt",2230 mAh Battery,"4.7 inches, 750 x 1334 px Display",13 MP Rear & 7 MP Front Camera,iOS v10,No FM Radio
656,658,Apple iPhone SE 2020,39900,63.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi, NFC","A13 Bionic, Hexa Core, 2.65 GHz Processor","3 GB RAM, 64 GB inbuilt",1821 mAh Battery with 18W Fast Charging,"4.7 inches, 750 x 1334 px Display",12 MP Rear & 7 MP Front Camera,iOS v13,No FM Radio
734,736,Huawei Nova 9,29990,83.0,"Dual Sim, 3G, 4G, Wi-Fi, NFC","Snapdragon 778G , Octa Core, 2.4 GHz Processor","8 GB RAM, 128 GB inbuilt",4300 mAh Battery with 66W Fast Charging,"6.57 inches, 1080 x 2340 px, 120 Hz Display wi...",50 MP Quad Rear & 32 MP Front Camera,HarmonyOS v2.0,No FM Radio
884,886,Huawei Nova 10,29990,82.0,"Dual Sim, 3G, 4G, Wi-Fi","Snapdragon 778G, Octa Core, 2.4 GHz Processor","8 GB RAM, 128 GB inbuilt",4000 mAh Battery with 66W Fast Charging,"6.67 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 60 MP Front ...,HarmonyOS,No FM Radio

In [45]:
idx=temp_df.index
df1.loc[idx,['card','os']]=df1.loc[idx,['card','os']].shift(1,axis=1) #right shift
df1['card'].value_counts().reset_index()
#card column is solved

                                   card  count
0      Memory Card Supported, upto 1 TB    171
1             Memory Card Not Supported    129
2    Memory Card Supported, upto 512 GB    105
3       Memory Card (Hybrid), upto 1 TB     91
4                 Memory Card Supported     90
5    Memory Card Supported, upto 256 GB     89
6                  Memory Card (Hybrid)     31
7     Memory Card (Hybrid), upto 256 GB     15
8     Memory Card (Hybrid), upto 512 GB     11
9    Memory Card Supported, upto 128 GB      7
10     Memory Card Supported, upto 2 TB      5
11    Memory Card Supported, upto 32 GB      5
12    Memory Card (Hybrid), upto 128 GB      3
13     Memory Card (Hybrid), upto 64 GB      3
14      Memory Card (Hybrid), upto 2 TB      3
15  Memory Card Supported, upto 1000 GB      1

In [46]:
df1['os'].value_counts().reset_index()

                                 os  count
0                       Android v12    394
1                       Android v11    274
2                       Android v13     91
3                       Android v10     69
4                Android v9.0 (Pie)     29
5                     Android v10.0     23
6                           iOS v16     15
7                           iOS v15     12
8               Android v8.1 (Oreo)     10
9                           iOS v14      6
10              Android v8.0 (Oreo)      4
11                    Android v11.0      4
12                          iOS v13      4
13                        iOS v15.0      3
14                    Android v12.1      2
15                         EMUI v12      2
16       Android v6.0 (Marshmallow)      2
17        Android v5.1.1 (Lollipop)      2
18                   HarmonyOS v2.0      2
19                     Harmony v2.0      2
20                        iOS v14.0      2
21            Android v7.1 (Nougat)      1
22                RTOS (Series 30+)      1
23                        HarmonyOS      1
24                          Android      1
25                 Hongmeng OS v4.0      1
26          Android v4.4.2 (KitKat)      1
27                          iOS v10      1
28  Pragati OS (Powered by Android)      1
29                        Bluetooth      1
30                 Hongmeng OS v3.0      1
31          Android v5.1 (Lollipop)      1
32                          iOS v17      1
33                        iOS v12.3      1
34                        iOS v13.0      1
35                     HarmonyOS v2      1
36                 Android v9 (Pie)      1

In [50]:
#here only one row have the value "Bluetooth" Rest seems good.
df1.loc[df1[df1['os'].str.contains('Bluetooth',na=False)].index,'os']=np.nan

In [51]:
df1['os'].value_counts().reset_index()

                                 os  count
0                       Android v12    394
1                       Android v11    274
2                       Android v13     91
3                       Android v10     69
4                Android v9.0 (Pie)     29
5                     Android v10.0     23
6                           iOS v16     15
7                           iOS v15     12
8               Android v8.1 (Oreo)     10
9                           iOS v14      6
10                    Android v11.0      4
11                          iOS v13      4
12              Android v8.0 (Oreo)      4
13                        iOS v15.0      3
14                   HarmonyOS v2.0      2
15        Android v5.1.1 (Lollipop)      2
16       Android v6.0 (Marshmallow)      2
17                     Harmony v2.0      2
18                         EMUI v12      2
19                    Android v12.1      2
20                        iOS v14.0      2
21                        HarmonyOS      1
22                          Android      1
23                 Hongmeng OS v4.0      1
24            Android v7.1 (Nougat)      1
25          Android v4.4.2 (KitKat)      1
26                RTOS (Series 30+)      1
27                          iOS v10      1
28  Pragati OS (Powered by Android)      1
29                 Hongmeng OS v3.0      1
30          Android v5.1 (Lollipop)      1
31                          iOS v17      1
32                        iOS v12.3      1
33                        iOS v13.0      1
34                     HarmonyOS v2      1
35                 Android v9 (Pie)      1

# END